import { k5Course } from "./base";

/**
 * math-2: Grade 2 math (Common Core), taught by Professor Pascal in
 * Riverbend Valley, a river town with a mill, bridges and a market.
 * Everything is read aloud, so sentences are short and written for the ear.
 */
export const math2 = k5Course("math", 2, [
  // 1. Fluent facts to 20 and one-step story problems
  {
    id: "math-2.facts-20",
    title: "Fast Facts to 20",
    minutes: 20,
    stage: "grammar",
    standards: ["2.OA.B.2", "2.OA.A.1"],
    read: [
      "Welcome to Riverbend Valley! The river has stopped, and the mill is quiet. Let's figure it out together, with math!",
      "Some facts we should know fast, as fast as a snap. 6 + 4 = 10. 9 + 9 = 18. These are our facts to 20.",
      "Smart tricks help us. Make a ten: 8 + 5 is 8 + 2 + 3. That is 10 + 3, so 13. Use doubles: 7 + 7 = 14, so 7 + 8 is one more. That's 15.",
      "Adding and subtracting are a team. If 9 + 6 = 15, then 15 - 6 = 9. The same three numbers make a fact family.",
      "Stories have math inside. A boat holds 12 fish. 5 swim away. How many are left? We write 12 - 5 = ☐. The box is the number we need. 12 - 5 = 7. Seven fish are left!",
    ].join("\n\n"),
    keyIdeas: [
      "🔟 Make a ten: 8 + 5 = 10 + 3 = 13.",
      "👯 Doubles help: 7 + 7 = 14, so 7 + 8 = 15.",
      "👨‍👩‍👧 Fact families: 9 + 6 = 15, so 15 - 6 = 9.",
      "📖 In a story, find the question, then add or subtract.",
    ],
    hook: {
      text: "The river in Riverbend Valley has stopped. The old mill wheel is still. The miller needs quick math to fix it. Are you ready to help?",
    },
    teach: [
      {
        title: "Make a Ten",
        teach:
          "Ten is a magic number. It is easy to add to. Look at 8 + 5. Eight wants to be ten. It needs 2 more. So take 2 from the 5. Now we have 10 + 3. That is 13! So 8 + 5 = 13. Try 9 + 4. Nine needs just 1 more. Then 10 + 3 = 13 again!",
        visual: {
          type: "flip",
          cards: [
            { front: "1 + ?", back: "1 + 9 = 10 🔟" },
            { front: "2 + ?", back: "2 + 8 = 10 🔟" },
            { front: "3 + ?", back: "3 + 7 = 10 🔟" },
            { front: "4 + ?", back: "4 + 6 = 10 🔟" },
            { front: "5 + ?", back: "5 + 5 = 10 🔟" },
          ],
        },
        probe: {
          type: "cloze",
          text: "8 + 5 is the same as 10 + {0}. So 8 + 5 = {1}.",
          blanks: [{ answers: ["3"] }, { answers: ["13"] }],
          bank: ["3", "13", "5", "12", "2"],
          hint: "Eight needs 2 more to make 10. What is left of the 5?",
          mistakes: [{ match: "12", coach: "Close! 8 needs 2 to make 10. The 5 has 3 left. So 10 + 3." }],
          seconds: 30,
        },
        think: {
          q: "What is 9 + 4?",
          choices: ["12", "13", "14"],
          answer: 1,
          why: "Nine needs 1 to make 10. The 4 has 3 left. 10 + 3 = 13.",
          hints: ["Nine needs 1 to make ten. Then 3 are left over.", "", "Count again: 9, then 10, 11, 12, 13."],
        },
        approaches: {
          analogy: "Making a ten is like filling an egg carton that holds 10. Fill the carton first, then count the extra eggs.",
          example: "7 + 6: Seven needs 3 to make 10. Take 3 from the 6, and 3 are left. 10 + 3 = 13. So 7 + 6 = 13.",
          simpler: {
            q: "What goes with 8 to make 10?",
            choices: ["1", "2", "3"],
            answer: 1,
            why: "8 + 2 = 10.",
            hints: ["8 + 1 is only 9. One more!", "", "8 + 3 is 11. That is one too many."],
          },
        },
      },
      {
        title: "Doubles and Fact Families",
        teach:
          "Doubles are two of the same. 6 + 6 = 12. 7 + 7 = 14. Doubles help with near doubles. 7 + 8 is one more than 7 + 7. So it is 15! Adding and taking away are a team. 9 + 6 = 15. So 15 - 6 = 9. And 15 - 9 = 6. These facts make a fact family. They use the same three numbers.",
        visual: {
          type: "flip",
          cards: [
            { front: "Double 5", back: "5 + 5 = 10 🖐️🖐️" },
            { front: "Double 6", back: "6 + 6 = 12 🥚 (an egg carton!)" },
            { front: "Double 7", back: "7 + 7 = 14" },
            { front: "Double 8", back: "8 + 8 = 16 🕷️ (a spider's legs, twice)" },
            { front: "Double 9", back: "9 + 9 = 18" },
          ],
        },
        probe: {
          type: "match",
          prompt: "Match each fact to its answer.",
          pairs: [
            { left: "6 + 6", right: "12" },
            { left: "7 + 8", right: "15" },
            { left: "15 - 6", right: "9" },
            { left: "9 + 9", right: "18" },
            { left: "14 - 7", right: "7" },
          ],
          hint: "Use doubles. 7 + 8 is one more than 7 + 7.",
          seconds: 45,
        },
        think: {
          q: "If 9 + 6 = 15, what is 15 - 6?",
          choices: ["6", "9", "21"],
          answer: 1,
          why: "It's the same fact family: 9, 6 and 15.",
          hints: ["6 is the part we took away. What part is left?", "", "Taking away makes it smaller, not bigger."],
        },
        approaches: {
          analogy: "A fact family is like a family that lives in one house. The same three numbers live together: 6, 9 and 15.",
          example: "8 + 9: I know 8 + 8 = 16. Nine is one more than 8. So 8 + 9 = 17. And then 17 - 9 = 8.",
          simpler: {
            q: "What is 6 + 6?",
            choices: ["10", "12", "13"],
            answer: 1,
            why: "Double 6 is 12.",
            hints: ["10 is 5 + 5. Six is a bit more.", "", "13 is one too many. Count six and six again."],
          },
        },
      },
      {
        title: "Story Problems",
        teach:
          "Math hides in stories. The miller has 14 sacks of wheat. He uses 6. How many are left? First, find the question. Then write a number sentence: 14 - 6 = a box. The box is the number we need. 14 - 6 = 8. Eight sacks are left! Some stories put together. Some take apart. Ask yourself which one it is.",
        visual: {
          type: "sort",
          prompt: "Put together or take apart?",
          buckets: ["Put together ➕", "Take apart ➖"],
          items: [
            { text: "🦆 3 ducks join 5 ducks", bucket: 0 },
            { text: "🍎 7 apples, 2 get eaten", bucket: 1 },
            { text: "🐟 A boat has 9 fish, 4 jump out", bucket: 1 },
            { text: "🐚 Ana has 6 shells and finds 5 more", bucket: 0 },
          ],
        },
        probe: {
          type: "number",
          prompt: "The miller has 14 sacks of wheat 🌾. He uses 6. How many sacks are left?",
          answer: 8,
          unit: "sacks",
          hint: "Start at 14 and count back 6. Or think: 6 + what = 14?",
          mistakes: [{ match: "20", coach: "He used some sacks, so there are fewer now. Take away 6." }],
          seconds: 40,
        },
        think: {
          q: "A cart has 8 apples. 5 more are added. Which number sentence fits?",
          choices: ["8 - 5 = ☐", "8 + 5 = ☐", "5 - 8 = ☐"],
          answer: 1,
          why: "Apples were added, so we put together: 8 + 5.",
          hints: ["Apples were added, so the pile gets bigger.", "", "We can't take 8 from 5 here. Apples were added."],
        },
        approaches: {
          analogy: "A story problem is like a riddle. Read it, find the question, then pick your tool: add to put together, subtract to take apart.",
          example: "Tom has 9 marbles. He gets 7 more. Put together: 9 + 7. Nine needs 1 to make 10, and 6 are left. 10 + 6 = 16 marbles.",
          simpler: {
            q: "3 birds sit on a fence. 2 more land. Do we add or subtract?",
            choices: ["Add", "Subtract", "Neither"],
            answer: 0,
            why: "More birds came, so we add.",
            hints: ["", "Birds came, so the group got bigger.", "There are numbers here, so we can do math with them."],
          },
        },
      },
    ],
    activity: {
      type: "sequence",
      prompt: "Put the make-a-ten steps for 9 + 5 in order.",
      steps: ["Start with 9 + 5.", "9 needs 1 to make 10.", "Take 1 from the 5. Now 4 are left.", "10 + 4 = 14.", "So 9 + 5 = 14!"],
    },
    explain: {
      prompt: "How would you solve 8 + 6 with make a ten? Tell it like you're teaching a friend.",
      keyPoints: ["8 needs 2 more to make 10", "Take 2 from the 6, which leaves 4", "10 + 4 = 14"],
    },
    mastery: [
      {
        type: "number",
        prompt: "What is 7 + 8?",
        answer: 15,
        hint: "Double 7 is 14. And 8 is one more than 7.",
        mistakes: [{ match: "14", coach: "That's 7 + 7. Eight is one more than 7." }],
        seconds: 20,
      },
      {
        type: "cloze",
        text: "9 + 7 = {0}. So 16 - 7 = {1}.",
        blanks: [{ answers: ["16"] }, { answers: ["9"] }],
        bank: ["16", "9", "7", "15", "17"],
        hint: "9, 7 and 16 are one fact family.",
        seconds: 30,
      },
      {
        type: "build",
        prompt: "12 frogs 🐸 sit on a log. 4 hop away. Build the number sentence.",
        tiles: ["12", "-", "4", "=", "8"],
        distractors: ["+", "16"],
        hint: "Frogs hopped away, so take away.",
        seconds: 40,
      },
      {
        type: "match",
        prompt: "Match each fact to its answer.",
        pairs: [
          { left: "5 + 8", right: "13" },
          { left: "9 + 9", right: "18" },
          { left: "11 - 3", right: "8" },
          { left: "20 - 10", right: "10" },
        ],
        hint: "Use make a ten and doubles.",
        seconds: 40,
      },
    ],
    check: [
      { q: "What is 6 + 7?", choices: ["12", "13", "14"], answer: 1, why: "Double 6 is 12, and one more is 13." },
      { q: "Which fact is in the same family as 4 + 9 = 13?", choices: ["13 - 9 = 4", "13 + 4 = 17", "9 - 4 = 5"], answer: 0, why: "It uses the same three numbers: 4, 9 and 13." },
      { q: "Sam has 15 grapes. He eats 7. How many are left?", choices: ["22", "9", "8"], answer: 2, why: "Eating takes grapes away: 15 - 7 = 8." },
      { q: "Which pair makes 10?", choices: ["4 and 5", "3 and 7", "2 and 9"], answer: 1, why: "3 + 7 = 10." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, play Make Ten with a deck of cards (take out the face cards). Lay cards face up and find pairs that add to 10, like 3 and 7. Then have your grown-up call out 5 add or subtract facts to 20 and answer them fast.",
      rubric: ["Found at least 5 pairs that make 10", "Said each pair's fact out loud", "Answered 5 quick facts to 20"],
    },
  },

  // 2. Place value to 1000
  {
    id: "math-2.place-value",
    title: "Hundreds, Tens and Ones",
    minutes: 20,
    stage: "grammar",
    standards: ["2.NBT.A.1", "2.NBT.A.3"],
    read: [
      "At the Riverbend market, beans come in groups. Ten loose beans fill a bag. That bag is one ten. Ten bags fill a box. That box is one hundred. A hundred is a bundle of ten tens.",
      "Look at the number 352. It has three digits. Each digit has a place. The 3 is in the hundreds place. It means 3 hundreds, or 300. The 5 is in the tens place. It means 5 tens, or 50. The 2 is in the ones place. It means 2 ones.",
      "We can write 352 in expanded form: 300 + 50 + 2. We can write it in words: three hundred fifty-two.",
      "Zero holds a place too. In 405, there are no tens. The zero keeps the 4 in the hundreds place. Without it, we would have 45, a much smaller number!",
    ].join("\n\n"),
    keyIdeas: [
      "🫘 Ten ones make a ten. 👜 Ten tens make a hundred. 📦",
      "Each digit's place tells its value: in 352, the 3 means 300.",
      "Expanded form shows each place: 352 = 300 + 50 + 2.",
      "Zero holds a place: 405 has no tens.",
    ],
    hook: {
      text: "The market in Riverbend sells beans in bags and boxes. Ten loose beans fill a bag. Ten bags fill a box! How many beans is that?",
    },
    teach: [
      {
        title: "Ten Tens Make a Hundred",
        teach:
          "Let's count beans! Ten loose beans fill one bag. That bag is one ten. Now fill ten bags. Ten bags of ten is one hundred beans! We pack them in a box. So one box is one hundred. Ten ones make a ten. Ten tens make a hundred. Big numbers are just bundles of bundles.",
        visual: {
          type: "flip",
          cards: [
            { front: "1 one", back: "🫘 one bean" },
            { front: "1 ten", back: "👜 a bag of 10 beans" },
            { front: "1 hundred", back: "📦 a box of 10 bags = 100 beans" },
            { front: "10 tens", back: "= 1 hundred!" },
          ],
        },
        probe: {
          type: "cloze",
          text: "Ten ones make one {0}. Ten tens make one {1}.",
          blanks: [{ answers: ["ten"] }, { answers: ["hundred"] }],
          bank: ["ten", "hundred", "thousand", "one"],
          hint: "Bundle the small ones into the next bigger group.",
          seconds: 25,
        },
        think: {
          q: "How many tens are in 100?",
          choices: ["1", "10", "100"],
          answer: 1,
          why: "Ten bags of ten beans make one hundred.",
          hints: ["One hundred is one box, but how many bags are inside?", "", "100 is the number of beans, not the number of bags."],
        },
        approaches: {
          analogy: "It's like money: 10 pennies trade for 1 dime, and 10 dimes trade for 1 dollar. Ones, tens and hundreds work the same way.",
          example: "Count 10 bags of 10 beans by tens: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100. Ten tens is 100.",
          simpler: {
            q: "How many ones make a ten?",
            choices: ["5", "10", "100"],
            answer: 1,
            why: "Ten ones make one ten.",
            hints: ["5 is only half of a ten.", "", "100 ones make a hundred. A ten is smaller."],
          },
        },
      },
      {
        title: "Every Digit Has a Place",
        teach:
          "Look at 352. Each digit has a job. The 3 is in the hundreds place. It means 300. The 5 is in the tens place. It means 50. The 2 is in the ones place. It means just 2. Same digit, new place, new value! The 5 in 352 is worth 50. But the 5 in 125 is worth only 5.",
        visual: {
          type: "hotspots",
          title: "The number 352",
          center: "352",
          spots: [
            { label: "Hundreds: 3", icon: "📦", detail: "3 boxes of 100 = 300" },
            { label: "Tens: 5", icon: "👜", detail: "5 bags of 10 = 50" },
            { label: "Ones: 2", icon: "🫘", detail: "2 loose beans = 2" },
          ],
        },
        probe: {
          type: "match",
          prompt: "Each 📦 is 100, each 👜 is 10, and each 🫘 is 1. Match each picture to its number.",
          pairs: [
            { left: "📦📦 👜👜👜 🫘🫘🫘🫘", right: "234" },
            { left: "📦 👜👜👜👜👜 🫘", right: "151" },
            { left: "📦📦📦📦 🫘🫘", right: "402" },
            { left: "📦📦📦 👜👜👜👜👜👜👜", right: "370" },
          ],
          hint: "Count the boxes for hundreds, the bags for tens, and the beans for ones.",
          seconds: 50,
        },
        think: {
          q: "In 472, what is the 7 worth?",
          choices: ["7", "70", "700"],
          answer: 1,
          why: "The 7 is in the tens place, so it means 7 tens, or 70.",
          hints: ["The 7 is in the tens place, not the ones place.", "", "The 4 is in the hundreds place, not the 7."],
        },
        approaches: {
          analogy: "Places are like seats in a row at the theater. The hundreds seat is the best seat: a digit sitting there is worth the most.",
          example: "In 638, the 6 is in the hundreds place, so it means 600. The 3 is in the tens place, so it means 30. The 8 means 8 ones.",
          simpler: {
            q: "In 25, which digit is in the tens place?",
            choices: ["2", "5", "25"],
            answer: 0,
            why: "The 2 is on the left, in the tens place. It means 20.",
            hints: ["", "The 5 is in the ones place, on the right.", "25 is the whole number. Pick one digit."],
          },
        },
      },
      {
        title: "Three Ways to Write a Number",
        teach:
          "We can write one number three ways. First, with digits: 352. Second, in expanded form: 300 + 50 + 2. That shows what each digit is worth. Third, in words: three hundred fifty-two. Watch out for zero! In 405 there are no tens. Zero holds the tens place. So the expanded form is 400 + 5.",
        visual: {
          type: "compare",
          left: { title: "Digits", points: ["352", "405", "690"] },
          right: { title: "Expanded form", points: ["300 + 50 + 2", "400 + 5", "600 + 90"] },
        },
        probe: {
          type: "cloze",
          text: "Expanded form: 528 = {0} + {1} + 8",
          blanks: [{ answers: ["500"] }, { answers: ["20"] }],
          bank: ["500", "20", "50", "2", "5"],
          hint: "The 5 is in the hundreds place. The 2 is in the tens place.",
          mistakes: [
            { match: "5", coach: "The 5 is in the hundreds place, so it is worth 500." },
            { match: "2", coach: "The 2 is in the tens place, so it is worth 20." },
          ],
          seconds: 35,
        },
        think: {
          q: "Which number is 400 + 5?",
          choices: ["45", "405", "450"],
          answer: 1,
          why: "4 hundreds, 0 tens and 5 ones is 405.",
          hints: ["45 has only 4 tens. We need 4 hundreds.", "", "450 has 5 tens. We need 5 ones."],
        },
        approaches: {
          analogy: "Expanded form is like opening a lunchbox and laying out each thing: the sandwich, the apple and the cookie. The whole lunch is all of them together.",
          example: "Six hundred thirteen: 6 hundreds is 600, 1 ten is 10, and 3 ones is 3. 600 + 10 + 3 = 613.",
          simpler: {
            q: "What is 300 + 40 + 1?",
            choices: ["341", "3401", "314"],
            answer: 0,
            why: "3 hundreds, 4 tens and 1 one is 341.",
            hints: ["", "Too many digits! 300 + 40 + 1 is a three-digit number.", "Put the 4 tens in the tens place and the 1 in the ones place."],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "What is the 6 worth in each number?",
      buckets: ["6 ones (6)", "6 tens (60)", "6 hundreds (600)"],
      items: [
        { text: "416", bucket: 0 },
        { text: "263", bucket: 1 },
        { text: "605", bucket: 2 },
        { text: "96", bucket: 0 },
        { text: "168", bucket: 1 },
        { text: "642", bucket: 2 },
        { text: "860", bucket: 1 },
        { text: "6", bucket: 0 },
      ],
    },
    explain: {
      prompt: "What does each digit in 247 mean? Explain it like a shopkeeper counting boxes, bags and beans.",
      keyPoints: ["The 2 means 2 hundreds, or 200", "The 4 means 4 tens, or 40", "The 7 means 7 ones", "247 = 200 + 40 + 7"],
    },
    mastery: [
      {
        type: "number",
        prompt: "📦📦📦 👜 🫘🫘🫘🫘🫘🫘. Each 📦 is 100 and each 👜 is 10. How many beans in all?",
        answer: 316,
        hint: "3 hundreds, 1 ten and 6 ones.",
        mistakes: [{ match: "361", coach: "There is only 1 bag of ten. Check the tens place." }],
        seconds: 40,
      },
      {
        type: "cloze",
        text: "Write 709 in words: seven hundred {0}.",
        blanks: [{ answers: ["nine"] }],
        bank: ["nine", "ninety", "seventy", "ninety-nine"],
        hint: "The 0 means there are no tens. What are the ones?",
        mistakes: [{ match: "ninety", coach: "The 0 is in the tens place, so there are no tens. 709 has 9 ones." }],
        seconds: 30,
      },
      {
        type: "build",
        prompt: "Build 836 in expanded form.",
        tiles: ["800", "+ 30", "+ 6"],
        distractors: ["+ 3", "80", "+ 60"],
        hint: "The 8 is worth 800, the 3 is worth 30, and the 6 is worth 6.",
        seconds: 40,
      },
      {
        type: "match",
        prompt: "Match the words to the number.",
        pairs: [
          { left: "two hundred sixteen", right: "216" },
          { left: "two hundred sixty", right: "260" },
          { left: "six hundred two", right: "602" },
          { left: "six hundred twenty", right: "620" },
        ],
        hint: "Listen for the hundreds first, then the tens, then the ones.",
        seconds: 45,
      },
    ],
    check: [
      { q: "What is the 9 worth in 593?", choices: ["9", "90", "900"], answer: 1, why: "The 9 is in the tens place, so it means 9 tens, or 90." },
      { q: "How many tens make one hundred?", choices: ["10", "100", "1"], answer: 0, why: "Ten tens make one hundred." },
      { q: "Which number is 600 + 4?", choices: ["64", "640", "604"], answer: 2, why: "6 hundreds, 0 tens and 4 ones is 604." },
      { q: "Which number is three hundred eighty-one?", choices: ["318", "381", "831"], answer: 1, why: "3 hundreds, 8 tens and 1 one is 381." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, make bundles of ten with dry beans or pasta. Put 10 in each cup or baggie. Show the number 124 with your bundles and loose pieces. Then write 124 in expanded form.",
      rubric: ["Made bundles of exactly 10", "Showed 124 as 12 tens and 4 ones (1 hundred, 2 tens and 4 ones)", "Wrote 100 + 20 + 4"],
    },
  },

  // 3. Skip counting, odd and even
  {
    id: "math-2.skip-odd-even",
    title: "Skip Counting, Odd and Even",
    minutes: 20,
    stage: "grammar",
    standards: ["2.NBT.A.2", "2.OA.C.3"],
    read: [
      "Skip counting means counting by the same jump each time. By 5s: 5, 10, 15, 20, 25. By 10s: 10, 20, 30, 40, 50. By 100s: 100, 200, 300, 400, 500. Skip counting is a fast way to count big groups. We can count all the way to 1000!",
      "Numbers can be odd or even. An even number can be split into pairs with none left over. 8 socks make 4 pairs. An odd number always has one left over. 7 socks make 3 pairs, and one sock is alone!",
      "Even numbers end in 0, 2, 4, 6 or 8. Odd numbers end in 1, 3, 5, 7 or 9. An even number is a double, too. 8 = 4 + 4. 12 = 6 + 6. Two equal groups, every time.",
    ].join("\n\n"),
    keyIdeas: [
      "🐸 Skip count by 5s, 10s and 100s to count fast.",
      "🧦 Even: everything pairs up. Odd: one is left over.",
      "Even numbers end in 0, 2, 4, 6 or 8.",
      "Every even number is a double, like 12 = 6 + 6.",
    ],
    hook: {
      text: "Hop, hop, hop! Frogs on the river stones jump in big skips. Counting by ones is slow. Let's skip count like the frogs!",
    },
    teach: [
      {
        title: "Skip Count by 5s, 10s and 100s",
        teach:
          "Skip counting is counting in jumps. Each jump is the same size. Count nickels by 5s: 5, 10, 15, 20. Count dimes by 10s: 10, 20, 30, 40. Count boxes of 100: 100, 200, 300, 400. You can start at other numbers too. Start at 230 and count by 10s: 240, 250, 260. Only the tens digit changes!",
        visual: {
          type: "flip",
          cards: [
            { front: "By 5s", back: "5, 10, 15, 20, 25, 30 🖐️" },
            { front: "By 10s", back: "10, 20, 30, 40, 50 🔟" },
            { front: "By 100s", back: "100, 200, 300 ... all the way to 1000 📦" },
            { front: "From 230 by 10s", back: "240, 250, 260, 270" },
          ],
        },
        probe: {
          type: "cloze",
          text: "Count by 5s: 35, 40, {0}, 50, {1}.",
          blanks: [{ answers: ["45"] }, { answers: ["55"] }],
          bank: ["45", "55", "41", "60", "51"],
          hint: "Add 5 each time.",
          seconds: 30,
        },
        think: {
          q: "Count by 100s: 300, 400, 500, ___?",
          choices: ["501", "510", "600"],
          answer: 2,
          why: "Each jump is 100, so 500 + 100 = 600.",
          hints: ["That's counting by 1s. Jump by 100!", "That's a jump of 10. Jump by 100.", ""],
        },
        approaches: {
          analogy: "Skip counting is like climbing stairs two or more at a time. Every step is the same size, so you get to the top faster.",
          example: "Count 6 nickels by 5s: 5, 10, 15, 20, 25, 30. Six nickels is 30 cents.",
          simpler: {
            q: "Count by 10s: 10, 20, 30, ___?",
            choices: ["31", "40", "50"],
            answer: 1,
            why: "30 + 10 = 40.",
            hints: ["31 is only one more. Jump by ten!", "", "50 skips too far. Just one jump of 10."],
          },
        },
      },
      {
        title: "Odd or Even?",
        teach:
          "Let's pair up socks! Put socks in pairs, two by two. If every sock has a buddy, the number is even. If one sock is left alone, the number is odd. 6 socks make 3 pairs. Even! 7 socks make 3 pairs and one extra. Odd! Here is a trick. Look at the last digit. Even numbers end in 0, 2, 4, 6 or 8.",
        visual: {
          type: "sort",
          prompt: "Pair them up! Odd or even?",
          buckets: ["Even (all have buddies)", "Odd (one left over)"],
          items: [
            { text: "🧦🧦🧦🧦", bucket: 0 },
            { text: "🧦🧦🧦", bucket: 1 },
            { text: "🍎🍎🍎🍎🍎🍎", bucket: 0 },
            { text: "🐸🐸🐸🐸🐸", bucket: 1 },
            { text: "⭐", bucket: 1 },
            { text: "🦆🦆🦆🦆🦆🦆🦆🦆", bucket: 0 },
          ],
        },
        probe: {
          type: "sort",
          prompt: "Is each number odd or even?",
          buckets: ["Odd", "Even"],
          items: [
            { text: "14", bucket: 1 },
            { text: "9", bucket: 0 },
            { text: "20", bucket: 1 },
            { text: "17", bucket: 0 },
            { text: "6", bucket: 1 },
            { text: "11", bucket: 0 },
          ],
          hint: "Look at the last digit. 0, 2, 4, 6 and 8 are even.",
          seconds: 40,
        },
        think: {
          q: "Is 15 odd or even?",
          choices: ["Odd", "Even", "Both"],
          answer: 0,
          why: "15 ends in 5. Pair them up and one is left over.",
          hints: ["", "15 ends in 5. Pairing up 15 things always leaves one alone.", "A number is either odd or even, never both."],
        },
        approaches: {
          analogy: "Odd and even is like kids lining up with a partner. If everyone has a partner, it's even. If one kid has no partner, it's odd.",
          example: "13 socks: pair them up. 2, 4, 6, 8, 10, 12. That's 6 pairs, and 1 sock is left. So 13 is odd.",
          simpler: {
            q: "4 socks 🧦🧦🧦🧦. Does every sock have a buddy?",
            choices: ["Yes", "No", "Can't tell"],
            answer: 0,
            why: "4 socks make 2 pairs with none left over.",
            hints: ["", "Pair them: two pairs and none left over.", "Try pairing them one by one."],
          },
        },
      },
      {
        title: "Even Numbers Are Doubles",
        teach:
          "Every even number can be split into two equal groups. 10 is 5 + 5. 12 is 6 + 6. 16 is 8 + 8. We call these doubles. Now try an odd number, like 9. Make 4 + 4. One is left over! Odd numbers can't split into two equal groups. So even numbers are doubles. Odd numbers are not.",
        visual: {
          type: "compare",
          left: { title: "Even = a double", points: ["8 = 4 + 4", "14 = 7 + 7", "18 = 9 + 9"] },
          right: { title: "Odd = one left over", points: ["7 = 3 + 3 + 1", "11 = 5 + 5 + 1", "15 = 7 + 7 + 1"] },
        },
        probe: {
          type: "match",
          prompt: "Match each even number to its double.",
          pairs: [
            { left: "10", right: "5 + 5" },
            { left: "14", right: "7 + 7" },
            { left: "18", right: "9 + 9" },
            { left: "8", right: "4 + 4" },
            { left: "12", right: "6 + 6" },
          ],
          hint: "Split the number into two equal groups.",
          seconds: 40,
        },
        think: {
          q: "Which shows 16 as a double?",
          choices: ["8 + 8", "10 + 6", "9 + 7"],
          answer: 0,
          why: "A double is two equal numbers: 8 + 8 = 16.",
          hints: ["", "Those add to 16, but 10 and 6 aren't equal.", "Those add to 16, but 9 and 7 are not the same."],
        },
        approaches: {
          analogy: "A double is like sharing cookies fairly with a friend. If you each get the same number with none left over, the total was even.",
          example: "Is 18 even? Split it: 9 + 9 = 18. Two equal groups, none left over. Yes, 18 is even!",
          simpler: {
            q: "What is 3 + 3?",
            choices: ["5", "6", "7"],
            answer: 1,
            why: "Double 3 is 6.",
            hints: ["Count again: 3, then 4, 5, 6.", "", "That's one too many. Three and three is six."],
          },
        },
      },
    ],
    activity: {
      type: "sequence",
      prompt: "Count by 10s from 470. Put the numbers in order.",
      steps: ["470", "480", "490", "500", "510"],
    },
    explain: {
      prompt: "How can you tell if a number is odd or even? Use socks or cookies to explain.",
      keyPoints: ["Pair things up two by two", "Even numbers have no leftovers", "Odd numbers have one left over", "Even numbers are doubles, like 6 + 6"],
    },
    mastery: [
      {
        type: "place",
        prompt: "Count by 100s! Put each number on the line.",
        min: 0,
        max: 1000,
        step: 100,
        tolerance: 0,
        items: [
          { label: "300", value: 300 },
          { label: "700", value: 700 },
          { label: "1000", value: 1000 },
        ],
        hint: "Each jump on the line is 100.",
        seconds: 30,
      },
      {
        type: "cloze",
        text: "Count by 10s: 670, 680, {0}, {1}, 710.",
        blanks: [{ answers: ["690"] }, { answers: ["700"] }],
        bank: ["690", "700", "681", "790", "800"],
        hint: "After 690, ten more is the next hundred.",
        mistakes: [{ match: "790", coach: "Only the tens go up by one. After 690 comes 700." }],
        seconds: 35,
      },
      {
        type: "sort",
        prompt: "Odd or even?",
        buckets: ["Odd", "Even"],
        items: [
          { text: "🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪", bucket: 1 },
          { text: "🍪🍪🍪🍪🍪🍪🍪", bucket: 0 },
          { text: "23", bucket: 0 },
          { text: "38", bucket: 1 },
          { text: "50", bucket: 1 },
        ],
        hint: "Pair them up, or look at the last digit.",
        seconds: 40,
      },
      {
        type: "number",
        prompt: "Count by 5s. How many fingers are on 7 hands? 🖐️🖐️🖐️🖐️🖐️🖐️🖐️",
        answer: 35,
        hint: "Count by 5s seven times: 5, 10, 15 ...",
        mistakes: [{ match: "30", coach: "That's 6 hands. Count one more jump of 5." }],
        seconds: 30,
      },
    ],
    check: [
      { q: "Which number is even?", choices: ["13", "24", "19"], answer: 1, why: "24 ends in 4. It splits into two equal groups: 12 + 12." },
      { q: "Count by 5s: 15, 20, 25, ___", choices: ["26", "30", "35"], answer: 1, why: "25 + 5 = 30." },
      { q: "Which number is odd?", choices: ["11", "16", "20"], answer: 0, why: "11 ends in 1. Pair them up and one is left over." },
      { q: "Count by 100s: 600, 700, 800, ___", choices: ["801", "810", "900"], answer: 2, why: "800 + 100 = 900." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, gather a pile of socks, spoons or toys. Pair them up two by two. Is the number odd or even? Then count a handful of coins or toes by 5s and 10s.",
      rubric: ["Paired up the objects two by two", "Said whether the number was odd or even and why", "Skip counted by 5s or 10s out loud"],
    },
  },

  // 4. Comparing numbers, 10 more and 100 more
  {
    id: "math-2.compare",
    title: "Which Is Greater?",
    minutes: 20,
    stage: "logic",
    standards: ["2.NBT.A.4", "2.NBT.B.8"],
    read: [
      "Which is bigger, 452 or 425? To compare, start with the biggest place. Look at the hundreds first. Both have 4 hundreds. That's a tie, so look at the tens. 452 has 5 tens. 425 has only 2 tens. So 452 is bigger!",
      "We use signs to compare. The sign > means greater than. The sign < means less than. The sign = means equal. Think of the sign as a hungry alligator's mouth. It always opens toward the bigger number. 452 > 425.",
      "We can add or take away 10 or 100 in our heads. Add 10, and only the tens digit grows by one. 364 + 10 = 374. Add 100, and only the hundreds digit grows by one. 364 + 100 = 464. Taking away works the same way, going down.",
    ].join("\n\n"),
    keyIdeas: [
      "Compare the hundreds first, then the tens, then the ones.",
      "🐊 > means greater than, < means less than. The mouth opens to the bigger number.",
      "10 more changes the tens digit. 100 more changes the hundreds digit.",
    ],
    hook: {
      text: "Two boats race down the river. One carries 452 apples. The other carries 425. Which boat has more? Let's figure it out together!",
    },
    teach: [
      {
        title: "Hundreds First",
        teach:
          "To compare two numbers, start at the biggest place. Look at the hundreds. Try 512 and 498. 5 hundreds beats 4 hundreds. So 512 is bigger, even though 498 has big tens and ones! If the hundreds tie, look at the tens. If the tens tie too, look at the ones. Compare place by place, from left to right.",
        visual: {
          type: "hotspots",
          title: "Compare 452 and 425",
          center: "452 ? 425",
          spots: [
            { label: "Hundreds", icon: "📦", detail: "4 and 4. A tie! Move on to the tens." },
            { label: "Tens", icon: "👜", detail: "5 tens and 2 tens. 5 is more, so 452 is greater." },
            { label: "Ones", icon: "🫘", detail: "We don't need the ones. The tens already decided it." },
          ],
        },
        probe: {
          type: "highlight",
          prompt: "Tap every number that is greater than 500.",
          sentences: ["499", "512", "350", "605", "590", "98"],
          correct: [1, 3, 4],
          hint: "Look at the hundreds digit first. It needs 5 hundreds or more.",
          seconds: 30,
        },
        think: {
          q: "Which is greater: 389 or 401?",
          choices: ["389", "401", "They are equal"],
          answer: 1,
          why: "4 hundreds is more than 3 hundreds.",
          hints: ["389 has big tens and ones, but look at the hundreds first.", "", "The digits are different, so they are not equal."],
        },
        approaches: {
          analogy: "Comparing numbers is like comparing piles of money. The pile with more hundred-dollar bills wins, no matter how many pennies the other pile has.",
          example: "Compare 736 and 763. Hundreds: 7 and 7, a tie. Tens: 3 and 6. Six tens is more, so 763 is greater.",
          simpler: {
            q: "Which is more: 3 hundreds or 2 hundreds?",
            choices: ["3 hundreds", "2 hundreds", "The same"],
            answer: 0,
            why: "3 boxes of 100 is more than 2 boxes of 100.",
            hints: ["", "2 boxes of 100 is less than 3 boxes.", "3 and 2 are different numbers."],
          },
        },
      },
      {
        title: "Greater Than, Less Than",
        teach:
          "Math has three signs for comparing. Greater than, less than, and equal. Greater than and less than look like an open mouth. Think of a hungry alligator. Its mouth opens toward the bigger number. It always wants to eat more! So 452 is greater than 425. The mouth opens to 452. And 425 is less than 452.",
        visual: {
          type: "flip",
          cards: [
            { front: ">", back: "greater than: 9 > 4 🐊" },
            { front: "<", back: "less than: 4 < 9 🐊" },
            { front: "=", back: "equal: 300 + 5 = 305" },
          ],
        },
        probe: {
          type: "cloze",
          text: "Fill in >, < or =. 318 {0} 381. 600 {1} 599. 250 {2} 200 + 50.",
          blanks: [{ answers: ["<"] }, { answers: [">"] }, { answers: ["="] }],
          bank: [">", "<", "="],
          hint: "The open mouth faces the bigger number. If they're the same, use =.",
          seconds: 45,
        },
        think: {
          q: "Which is true?",
          choices: ["245 > 254", "245 < 254", "245 = 254"],
          answer: 1,
          why: "4 tens is less than 5 tens, so 245 < 254.",
          hints: ["Check the tens: 4 tens is less than 5 tens.", "", "These numbers have different digits, so they're not equal."],
        },
        approaches: {
          analogy: "The greater than sign is like a hungry alligator. It always turns its mouth toward the bigger snack.",
          example: "Compare 670 and 607. The hundreds tie at 6. Tens: 7 and 0. Seven tens is more. So 670 > 607.",
          simpler: {
            q: "Which is bigger: 9 or 4?",
            choices: ["9", "4", "The same"],
            answer: 0,
            why: "9 comes after 4 when we count.",
            hints: ["", "4 is smaller. Count up: 4, 5, 6, 7, 8, 9.", "They are different numbers."],
          },
        },
      },
      {
        title: "10 More, 100 More",
        teach:
          "Adding 10 is easy in your head. Just add one to the tens digit. 364 and 10 more is 374. Adding 100? Add one to the hundreds digit. 364 and 100 more is 464. Taking away works the same way. 10 less than 364 is 354. 100 less than 364 is 264. Only one digit changes!",
        visual: {
          type: "compare",
          left: { title: "10 more or 10 less", points: ["364 → 374", "528 → 538", "750 → 740 (10 less)"] },
          right: { title: "100 more or 100 less", points: ["364 → 464", "528 → 628", "750 → 650 (100 less)"] },
        },
        probe: {
          type: "number",
          prompt: "What is 100 more than 247?",
          answer: 347,
          hint: "Add one to the hundreds digit. The tens and ones stay the same.",
          mistakes: [
            { match: "257", coach: "That's 10 more. 100 more changes the hundreds digit." },
            { match: "248", coach: "That's 1 more. 100 more changes the hundreds digit." },
          ],
          seconds: 20,
        },
        think: {
          q: "What is 10 less than 586?",
          choices: ["576", "486", "585"],
          answer: 0,
          why: "The tens digit goes down by one: 586 becomes 576.",
          hints: ["", "That's 100 less. 10 less changes the tens digit.", "That's 1 less. Take away a whole ten."],
        },
        approaches: {
          analogy: "Adding 10 is like putting one more bag of ten on the shelf. The bags go up by one, and the loose beans stay the same.",
          example: "What is 100 more than 619? The hundreds digit 6 goes up to 7. The tens and ones stay. So it's 719.",
          simpler: {
            q: "What is 10 more than 20?",
            choices: ["21", "30", "120"],
            answer: 1,
            why: "2 tens and 1 more ten is 3 tens: 30.",
            hints: ["That's 1 more. Add a whole ten.", "", "That's 100 more. Just add one ten."],
          },
        },
      },
    ],
    activity: {
      type: "sequence",
      prompt: "Put these numbers in order from least to greatest.",
      steps: ["199", "219", "291", "912", "921"],
    },
    explain: {
      prompt: "How do you know 503 is greater than 498? Explain it place by place.",
      keyPoints: ["Start with the hundreds place", "5 hundreds is more than 4 hundreds", "So 503 > 498, even though 498 has more tens and ones"],
    },
    mastery: [
      {
        type: "cloze",
        text: "Fill in > or <. 723 {0} 732. 480 {1} 408.",
        blanks: [{ answers: ["<"] }, { answers: [">"] }],
        bank: [">", "<", "="],
        hint: "The hundreds tie, so compare the tens.",
        seconds: 30,
      },
      {
        type: "number",
        prompt: "What is 10 less than 905?",
        answer: 895,
        hint: "There are 0 tens, so take the ten from the hundreds: 9 hundreds becomes 8 hundreds and 9 tens.",
        mistakes: [
          { match: "805", coach: "That's 100 less. Take away just 10." },
          { match: "904", coach: "That's 1 less. Take away a whole ten." },
        ],
        seconds: 40,
      },
      {
        type: "place",
        prompt: "Put each number on the line.",
        min: 100,
        max: 200,
        step: 10,
        tolerance: 0,
        items: [
          { label: "10 more than 120", value: 130 },
          { label: "100 less than 270", value: 170 },
          { label: "10 less than 120", value: 110 },
        ],
        hint: "Find each number first. Then find it on the line.",
        seconds: 45,
      },
      {
        type: "highlight",
        prompt: "Tap every number that is less than 350.",
        sentences: ["305", "530", "349", "350", "299"],
        correct: [0, 2, 4],
        hint: "350 is not less than itself. Check the hundreds, then the tens.",
        seconds: 30,
      },
    ],
    check: [
      { q: "Which number is the greatest?", choices: ["689", "698", "869"], answer: 2, why: "869 has 8 hundreds. The others have only 6." },
      { q: "What is 100 more than 452?", choices: ["462", "552", "453"], answer: 1, why: "The hundreds digit goes up by one: 552." },
      { q: "Which is true?", choices: ["310 > 301", "310 < 301", "310 = 301"], answer: 0, why: "The hundreds tie. 1 ten is more than 0 tens." },
      { q: "What is 10 more than 795?", choices: ["796", "895", "805"], answer: 2, why: "9 tens and 1 more ten is 10 tens, a new hundred: 805." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, write 6 three-digit numbers on cards, like house numbers or page numbers. Put them in order from least to greatest. Then pick two and say which is greater, using the words greater than or less than.",
      rubric: ["Ordered the numbers from least to greatest", "Compared the hundreds first, then the tens, then the ones", "Said a comparison out loud with greater than or less than"],
    },
  },

  // 5. Adding and subtracting within 100
  {
    id: "math-2.within-100",
    title: "Adding and Subtracting to 100",
    minutes: 20,
    stage: "logic",
    standards: ["2.NBT.B.5", "2.NBT.B.6", "2.NBT.B.9", "2.OA.A.1", "2.MD.B.6"],
    read: [
      "To add 36 + 47, we can add place by place. Tens first: 30 + 40 = 70. Ones next: 6 + 7 = 13. Then 70 + 13 = 83. When the ones make 10 or more, we get a new ten.",
      "To subtract, we can count up on a number line. For 62 - 38, start at 38. Jump 2 to get to 40. Jump 20 to get to 60. Jump 2 more to get to 62. The jumps add to 24. So 62 - 38 = 24.",
      "We can add four numbers too. Try 15 + 20 + 25 + 10. Look for friends that make tens. 15 + 25 = 40. Then 40 + 20 + 10 = 70.",
      "Some stories have two steps. A basket has 50 apples. Kids eat 12. Then they pick 20 more. First 50 - 12 = 38. Then 38 + 20 = 58 apples.",
    ].join("\n\n"),
    keyIdeas: [
      "Add tens with tens and ones with ones: 36 + 47 = 70 + 13 = 83.",
      "📏 Count up on a number line to subtract: 62 - 38 = 24.",
      "Check subtraction with addition: 24 + 38 = 62.",
      "Two-step stories: do step one, then use that answer in step two.",
    ],
    hook: {
      text: "It's market day! The baker sells 36 loaves in the morning. Then she sells 47 more in the afternoon. How many loaves is that? Big numbers need smart tools.",
    },
    teach: [
      {
        title: "Add Tens, Then Ones",
        teach:
          "Let's add 36 + 47. Break each number into tens and ones. Add the tens first. 30 + 40 = 70. Then add the ones. 6 + 7 = 13. Now put them together. 70 + 13 = 83. See what happened? The ones made 13. That's a new ten and 3 more. Place value keeps tens with tens and ones with ones.",
        visual: {
          type: "hotspots",
          title: "36 + 47",
          center: "36 + 47",
          spots: [
            { label: "Tens", icon: "👜", detail: "30 + 40 = 70" },
            { label: "Ones", icon: "🫘", detail: "6 + 7 = 13. That's a new ten and 3 ones!" },
            { label: "Together", icon: "🎉", detail: "70 + 13 = 83" },
          ],
        },
        probe: {
          type: "cloze",
          text: "Add 45 + 28. Tens: 40 + 20 = {0}. Ones: 5 + 8 = {1}. Total: {2}.",
          blanks: [{ answers: ["60"] }, { answers: ["13"] }, { answers: ["73"] }],
          bank: ["60", "13", "73", "63", "12"],
          hint: "Add the tens, then the ones, then put them together.",
          mistakes: [{ match: "63", coach: "The ones made 13. That's one more ten! 60 + 13 = 73." }],
          seconds: 50,
        },
        think: {
          q: "What is 25 + 34?",
          choices: ["59", "69", "49"],
          answer: 0,
          why: "Tens: 20 + 30 = 50. Ones: 5 + 4 = 9. 50 + 9 = 59.",
          hints: ["", "Check the tens: 20 + 30 = 50, not 60.", "Check the tens: 20 + 30 = 50, not 40."],
        },
        approaches: {
          analogy: "Adding tens and ones is like sorting laundry. Socks go with socks and shirts go with shirts. Count each pile, then put them together.",
          example: "54 + 29: Tens: 50 + 20 = 70. Ones: 4 + 9 = 13. Then 70 + 13 = 83.",
          simpler: {
            q: "What is 30 + 40?",
            choices: ["34", "70", "700"],
            answer: 1,
            why: "3 tens and 4 tens is 7 tens: 70.",
            hints: ["That's putting the digits side by side. Add 3 tens and 4 tens.", "", "That's too big. 3 tens and 4 tens is 7 tens."],
          },
        },
      },
      {
        title: "Jump on the Number Line",
        teach:
          "A number line helps us subtract. Let's find 62 - 38. Start at 38. Count up to 62 in jumps. Jump 2 to land on 40. Jump 20 to land on 60. Jump 2 more to land on 62. Now add the jumps. 2 + 20 + 2 = 24. So 62 - 38 = 24. Check it! 38 + 24 = 62. Adding checks subtracting.",
        visual: {
          type: "sequence",
          prompt: "Put the jumps from 38 to 62 in order.",
          steps: ["Start at 38", "Jump 2 to land on 40", "Jump 20 to land on 60", "Jump 2 to land on 62", "Add the jumps: 2 + 20 + 2 = 24"],
        },
        probe: {
          type: "place",
          prompt: "Start at 38. Where do you land? Put each jump on the number line.",
          min: 30,
          max: 70,
          step: 1,
          tolerance: 1,
          items: [
            { label: "38 + 2", value: 40 },
            { label: "38 + 10", value: 48 },
            { label: "38 + 22", value: 60 },
            { label: "38 + 24", value: 62 },
          ],
          hint: "Find 38 first. Then count up the jump.",
          seconds: 60,
        },
        think: {
          q: "What is 50 - 27?",
          choices: ["23", "33", "27"],
          answer: 0,
          why: "Count up from 27: 3 to get to 30, then 20 more to 50. 3 + 20 = 23.",
          hints: ["", "Count up from 27: 3 to get to 30, 20 more to 50. That's 23, not 33.", "27 is what we took away. Find what is left."],
        },
        approaches: {
          analogy: "Counting up on a number line is like walking to a friend's house and counting your steps. The steps you took are the difference.",
          example: "71 - 45: Start at 45. Jump 5 to 50. Jump 20 to 70. Jump 1 to 71. 5 + 20 + 1 = 26. So 71 - 45 = 26.",
          simpler: {
            q: "How far is it from 38 to 40?",
            choices: ["2", "8", "12"],
            answer: 0,
            why: "Count up: 39, 40. That's 2.",
            hints: ["", "That's too far. Count up: 39, 40.", "That's too far. Count up: 39, 40."],
          },
        },
      },
      {
        title: "Big Sums and Two-Step Stories",
        teach:
          "We can add four numbers at once. Try 15 + 20 + 25 + 10. Look for friends that make a ten. 15 + 25 = 40. Then 40 + 20 = 60. Then 60 + 10 = 70. Some stories have two steps. A basket has 50 apples. Kids eat 12. Then they pick 20 more. Step one: 50 - 12 = 38. Step two: 38 + 20 = 58 apples.",
        visual: {
          type: "flip",
          cards: [
            { front: "Friends first", back: "15 + 25 = 40 🤝" },
            { front: "Then the rest", back: "40 + 20 + 10 = 70" },
            { front: "Step 1 🍎", back: "50 - 12 = 38" },
            { front: "Step 2 🍎", back: "38 + 20 = 58" },
          ],
        },
        probe: {
          type: "number",
          prompt: "A boat has 25 fish 🐟. It catches 30 more. Then 15 fish are sold. How many fish are on the boat now?",
          answer: 40,
          unit: "fish",
          hint: "Step one: add the fish it caught. Step two: take away the fish that were sold.",
          mistakes: [
            { match: "55", coach: "That's after step one. Now take away the 15 fish that were sold." },
            { match: "70", coach: "The 15 fish were sold, so take them away. Don't add them." },
          ],
          seconds: 60,
        },
        think: {
          q: "What is 12 + 18 + 20 + 10?",
          choices: ["50", "60", "40"],
          answer: 1,
          why: "12 + 18 = 30. Then 30 + 20 + 10 = 60.",
          hints: ["Add again: 12 + 18 is 30, then 20 and 10 more.", "", "Don't forget one of the numbers. There are four to add."],
        },
        approaches: {
          analogy: "A two-step story is like a recipe. Do step one, then use what you made in step two.",
          example: "Mia has 40 stickers. She gives away 15, then gets 10 more. Step one: 40 - 15 = 25. Step two: 25 + 10 = 35 stickers.",
          simpler: {
            q: "What is 15 + 25?",
            choices: ["30", "40", "45"],
            answer: 1,
            why: "10 + 20 = 30, and 5 + 5 = 10 more. That's 40.",
            hints: ["Tens: 10 + 20 = 30. Then the ones 5 + 5 make another ten.", "", "Too many! 5 + 5 is 10, not 15."],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "Do the ones make a new ten?",
      buckets: ["Yes, the ones make 10 or more", "No new ten"],
      items: [
        { text: "27 + 15", bucket: 0 },
        { text: "41 + 36", bucket: 1 },
        { text: "58 + 34", bucket: 0 },
        { text: "62 + 23", bucket: 1 },
        { text: "19 + 19", bucket: 0 },
        { text: "30 + 45", bucket: 1 },
      ],
    },
    explain: {
      prompt: "How would you add 48 + 35? Explain each step, and say why it works.",
      keyPoints: ["Add the tens: 40 + 30 = 70", "Add the ones: 8 + 5 = 13", "13 is a new ten and 3 ones", "70 + 13 = 83"],
    },
    mastery: [
      {
        type: "number",
        prompt: "What is 53 + 39?",
        answer: 92,
        hint: "Tens: 50 + 30. Ones: 3 + 9. Then put them together.",
        mistakes: [{ match: "82", coach: "The ones made 12. That's another ten! 80 + 12 = 92." }],
        seconds: 40,
      },
      {
        type: "cloze",
        text: "Count up to find 80 - 46. Jump {0} to get to 50. Jump {1} to get to 80. So 80 - 46 = {2}.",
        blanks: [{ answers: ["4"] }, { answers: ["30"] }, { answers: ["34"] }],
        bank: ["4", "30", "34", "40", "36"],
        hint: "From 46, how far is it to 50? Then from 50 to 80?",
        seconds: 50,
      },
      {
        type: "build",
        prompt: "70 apples 🍎 are at the market. 28 are sold. Build the number sentence.",
        tiles: ["70", "-", "28", "=", "42"],
        distractors: ["+", "98"],
        hint: "Apples were sold, so take away. Count up from 28 to 70 to find the answer.",
        seconds: 50,
      },
      {
        type: "place",
        prompt: "Work out each one. Then put it on the number line.",
        min: 0,
        max: 100,
        step: 1,
        tolerance: 2,
        items: [
          { label: "20 + 25", value: 45 },
          { label: "50 + 30", value: 80 },
          { label: "90 - 75", value: 15 },
        ],
        hint: "Find each answer first, then find it on the line.",
        seconds: 60,
      },
    ],
    check: [
      { q: "What is 46 + 27?", choices: ["63", "73", "83"], answer: 1, why: "40 + 20 = 60, 6 + 7 = 13, and 60 + 13 = 73." },
      { q: "What is 90 - 35?", choices: ["55", "65", "45"], answer: 0, why: "Count up from 35: 5 to 40, then 50 to 90. 5 + 50 = 55." },
      { q: "Which fact checks 70 - 26 = 44?", choices: ["70 + 26 = 96", "44 - 26 = 18", "44 + 26 = 70"], answer: 2, why: "Adding the answer and the part taken away gives back the whole: 44 + 26 = 70." },
      { q: "What is 10 + 20 + 30 + 15?", choices: ["65", "75", "55"], answer: 1, why: "10 + 20 + 30 = 60, and 60 + 15 = 75." },
    ],
    task: {
      kind: "project",
      prompt: "Play store at home! With a grown-up, put price tags from 10¢ to 50¢ on 4 small things. Pick two things and add their prices. Then pick two and find how much more one costs by counting up.",
      rubric: ["Added two prices using tens and ones", "Found a difference by counting up", "Checked a subtraction with addition"],
    },
  },

  // 6. Adding and subtracting within 1000
  {
    id: "math-2.within-1000",
    title: "Adding and Subtracting to 1000",
    minutes: 20,
    stage: "logic",
    standards: ["2.NBT.B.7", "2.NBT.B.8", "2.NBT.B.9"],
    read: [
      "Big numbers work just like small ones. To add 245 + 132, add each place. Hundreds: 200 + 100 = 300. Tens: 40 + 30 = 70. Ones: 5 + 2 = 7. Then 300 + 70 + 7 = 377.",
      "Sometimes a place gets too full. In 158 + 167, the ones make 15. That's a new ten! Then the tens make 12 tens. That's a new hundred. 158 + 167 = 325.",
      "Subtracting can need a trade, too. For 342 - 118, there are not enough ones. Break apart one ten into 10 ones. Now 12 - 8 = 4. Then 3 tens - 1 ten = 2 tens, and 3 hundreds - 1 hundred = 2 hundreds. The answer is 224.",
      "Always check. Does the answer make sense? Adding checks subtracting: 224 + 118 = 342.",
    ].join("\n\n"),
    keyIdeas: [
      "Add hundreds, tens and ones, each in its own place.",
      "When a place gets 10 or more, make a new ten or a new hundred.",
      "When there aren't enough to take away, break apart a ten or a hundred.",
      "✅ Check subtraction with addition.",
    ],
    hook: {
      text: "The mill grinds 245 bags of flour on Monday. On Tuesday it grinds 132 more. That's a lot of flour! Let's add hundreds, tens and ones.",
    },
    teach: [
      {
        title: "Add Each Place",
        teach:
          "Let's add 245 + 132. Line up the places. Hundreds go with hundreds. Tens go with tens. Ones go with ones. Hundreds: 200 + 100 = 300. Tens: 40 + 30 = 70. Ones: 5 + 2 = 7. Now put it together. 300 + 70 + 7 = 377. That's 377 bags of flour!",
        visual: {
          type: "hotspots",
          title: "245 + 132",
          center: "245 + 132",
          spots: [
            { label: "Hundreds", icon: "📦", detail: "200 + 100 = 300" },
            { label: "Tens", icon: "👜", detail: "40 + 30 = 70" },
            { label: "Ones", icon: "🫘", detail: "5 + 2 = 7" },
            { label: "Total", icon: "🎉", detail: "300 + 70 + 7 = 377" },
          ],
        },
        probe: {
          type: "cloze",
          text: "Add 423 + 251. Hundreds: {0}. Tens: {1}. Ones: {2}. Total: {3}.",
          blanks: [{ answers: ["600"] }, { answers: ["70"] }, { answers: ["4"] }, { answers: ["674"] }],
          bank: ["600", "70", "4", "674", "764", "50"],
          hint: "400 + 200 for the hundreds, 20 + 50 for the tens, and 3 + 1 for the ones.",
          seconds: 60,
        },
        think: {
          q: "What is 312 + 456?",
          choices: ["768", "758", "868"],
          answer: 0,
          why: "300 + 400 = 700, 10 + 50 = 60, 2 + 6 = 8. So 768.",
          hints: ["", "Check the tens: 10 + 50 = 60.", "Check the hundreds: 300 + 400 = 700, not 800."],
        },
        approaches: {
          analogy: "Adding by place is like stacking blocks: big hundred blocks in one pile, ten-sticks in another, little cubes in another. Count each pile.",
          example: "531 + 246: Hundreds: 500 + 200 = 700. Tens: 30 + 40 = 70. Ones: 1 + 6 = 7. The total is 777.",
          simpler: {
            q: "What is 200 + 100?",
            choices: ["300", "201", "2100"],
            answer: 0,
            why: "2 hundreds and 1 hundred is 3 hundreds.",
            hints: ["", "That's only adding 1. Add a whole hundred.", "Don't write the numbers side by side. Add 2 hundreds and 1 hundred."],
          },
        },
      },
      {
        title: "Make a New Ten or Hundred",
        teach:
          "Sometimes a place gets too full. Let's add 158 + 167. Ones: 8 + 7 = 15. That's one ten and 5 ones. Move the new ten over to the tens. Tens: 5 + 6 + 1 = 12 tens. Twelve tens is one hundred and 2 tens. Move the new hundred over! Hundreds: 1 + 1 + 1 = 3. The answer is 325.",
        visual: {
          type: "sequence",
          prompt: "Put the steps for 158 + 167 in order.",
          steps: [
            "Ones: 8 + 7 = 15",
            "Make a new ten. Keep 5 ones.",
            "Tens: 5 + 6 + 1 = 12 tens",
            "Make a new hundred. Keep 2 tens.",
            "Hundreds: 1 + 1 + 1 = 3",
            "Answer: 325",
          ],
        },
        probe: {
          type: "number",
          prompt: "What is 276 + 148?",
          answer: 424,
          hint: "Ones: 6 + 8 = 14. Tens: 7 + 4 + 1 = 12. Make a new ten and a new hundred!",
          mistakes: [{ match: "314", coach: "Don't forget to move the new ten and the new hundred over." }],
          seconds: 60,
        },
        think: {
          q: "What is 365 + 227?",
          choices: ["592", "582", "5812"],
          answer: 0,
          why: "Ones: 5 + 7 = 12, so make a new ten. Tens: 6 + 2 + 1 = 9. Hundreds: 3 + 2 = 5. That's 592.",
          hints: ["", "The ones made 12. Move the new ten over: 6 + 2 + 1 = 9 tens.", "12 ones is 1 ten and 2 ones. Don't write 12 in one place."],
        },
        approaches: {
          analogy: "Making a new ten is like trading 10 pennies for a dime. When a place has 10 or more, trade them up to the next place.",
          example: "139 + 254: Ones: 9 + 4 = 13, so make a ten and keep 3. Tens: 3 + 5 + 1 = 9. Hundreds: 1 + 2 = 3. The answer is 393.",
          simpler: {
            q: "15 ones is the same as...",
            choices: ["1 ten and 5 ones", "15 tens", "5 tens and 1 one"],
            answer: 0,
            why: "15 = 10 + 5, so it's 1 ten and 5 ones.",
            hints: ["", "15 tens would be 150. We only have 15.", "Look again: 15 is 10 and 5."],
          },
        },
      },
      {
        title: "Break Apart to Subtract",
        teach:
          "Now let's subtract 342 - 118. Look at the ones. We have 2. We need to take away 8. Not enough! So break apart one ten into 10 ones. Now we have 12 ones and 3 tens. Ones: 12 - 8 = 4. Tens: 3 - 1 = 2. Hundreds: 3 - 1 = 2. The answer is 224. Check it. 224 + 118 = 342. Yes!",
        visual: {
          type: "flip",
          cards: [
            { front: "342", back: "3 hundreds, 4 tens, 2 ones" },
            { front: "Break a ten", back: "3 hundreds, 3 tens, 12 ones" },
            { front: "Take away 118", back: "12 - 8 = 4, 3 - 1 = 2, 3 - 1 = 2" },
            { front: "Answer", back: "224 ✅ (224 + 118 = 342)" },
          ],
        },
        probe: {
          type: "number",
          prompt: "What is 563 - 247?",
          answer: 316,
          hint: "3 ones is not enough to take away 7. Break apart a ten.",
          mistakes: [{ match: "324", coach: "You took 3 from 7. Instead, break apart a ten: 13 - 7 = 6." }],
          seconds: 60,
        },
        think: {
          q: "What is 452 - 136?",
          choices: ["316", "324", "326"],
          answer: 0,
          why: "Break a ten: 12 - 6 = 6. Tens: 4 - 3 = 1. Hundreds: 4 - 1 = 3. So 316.",
          hints: ["", "You took 2 from 6. Break a ten instead: 12 - 6 = 6.", "Check the tens: after breaking a ten, 4 tens are left, and 4 - 3 = 1."],
        },
        approaches: {
          analogy: "Breaking apart a ten is like breaking a dollar into dimes so you can pay. You still have the same money, just in smaller pieces.",
          example: "625 - 318: 5 ones is not enough to take 8. Break a ten: 15 - 8 = 7. Tens: 1 - 1 = 0. Hundreds: 6 - 3 = 3. The answer is 307.",
          simpler: {
            q: "Which is the same as 4 tens and 2 ones?",
            choices: ["3 tens and 12 ones", "4 tens and 12 ones", "2 tens and 4 ones"],
            answer: 0,
            why: "Break one ten into 10 ones: 3 tens and 12 ones is still 42.",
            hints: ["", "That's too many. Breaking a ten takes one ten away.", "That swaps the digits. Trade one ten for ten ones."],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "Does it need a trade?",
      buckets: ["Make a new ten or hundred", "Break apart a ten or hundred", "No trade needed"],
      items: [
        { text: "158 + 167", bucket: 0 },
        { text: "342 - 118", bucket: 1 },
        { text: "245 + 132", bucket: 2 },
        { text: "276 + 148", bucket: 0 },
        { text: "563 - 247", bucket: 1 },
        { text: "785 - 341", bucket: 2 },
        { text: "405 - 120", bucket: 1 },
        { text: "321 + 456", bucket: 2 },
      ],
    },
    explain: {
      prompt: "How do you solve 352 - 127? Explain what you do when there aren't enough ones.",
      keyPoints: ["2 ones is not enough to take away 7", "Break apart a ten into 10 ones", "12 - 7 = 5, 4 - 2 = 2, 3 - 1 = 2", "The answer is 225"],
    },
    mastery: [
      {
        type: "number",
        prompt: "What is 438 + 295?",
        answer: 733,
        hint: "Ones: 8 + 5 = 13. Tens: 3 + 9 + 1 = 13. Make a new ten and a new hundred.",
        mistakes: [{ match: "623", coach: "Don't forget to move the new ten and the new hundred over." }],
        seconds: 60,
      },
      {
        type: "cloze",
        text: "Mental math! 100 more than 640 is {0}. 10 less than 640 is {1}.",
        blanks: [{ answers: ["740"] }, { answers: ["630"] }],
        bank: ["740", "630", "650", "540"],
        hint: "100 more changes the hundreds digit. 10 less changes the tens digit.",
        seconds: 30,
      },
      {
        type: "match",
        prompt: "Match each problem to its answer.",
        pairs: [
          { left: "300 + 450", right: "750" },
          { left: "900 - 600", right: "300" },
          { left: "125 + 125", right: "250" },
          { left: "800 - 350", right: "450" },
        ],
        hint: "Work with hundreds and tens. 125 + 125 is a double!",
        seconds: 60,
      },
      {
        type: "place",
        prompt: "Work out each one. Then put it on the number line.",
        min: 0,
        max: 1000,
        step: 10,
        tolerance: 10,
        items: [
          { label: "200 + 300", value: 500 },
          { label: "1000 - 100", value: 900 },
          { label: "150 + 100", value: 250 },
        ],
        hint: "Find each answer first, then find it on the line.",
        seconds: 50,
      },
    ],
    check: [
      { q: "What is 324 + 152?", choices: ["476", "466", "486"], answer: 0, why: "300 + 100 = 400, 20 + 50 = 70, 4 + 2 = 6. So 476." },
      { q: "In 271 - 135, what should you do first?", choices: ["Add the ones", "Take away the hundreds and stop", "Break apart a ten, because 1 is less than 5"], answer: 2, why: "There is 1 one, and we need to take away 5. Break a ten to get 11 ones." },
      { q: "What is 10 more than 395?", choices: ["396", "405", "495"], answer: 1, why: "9 tens and 1 more ten is a new hundred: 405." },
      { q: "Which fact checks 500 - 180 = 320?", choices: ["320 + 180 = 500", "500 + 180 = 680", "320 - 180 = 140"], answer: 0, why: "The answer plus the part taken away gives back the whole." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, find two real numbers between 100 and 500, like pages in two books or steps on two walks. Add them place by place. Then subtract the smaller from the bigger, and check your answer with addition.",
      rubric: ["Added two three-digit numbers place by place", "Made a new ten or hundred when needed", "Subtracted and checked the answer with addition"],
    },
  },

  // 7. Measuring length, line plots and bar graphs
  {
    id: "math-2.measure",
    title: "Measure It and Graph It",
    minutes: 20,
    stage: "logic",
    standards: ["2.MD.A.1", "2.MD.A.2", "2.MD.A.3", "2.MD.A.4", "2.MD.B.5", "2.MD.B.6", "2.MD.D.9", "2.MD.D.10"],
    read: [
      "We measure to find how long something is. A ruler is 12 inches long. That's one foot. A yardstick is 3 feet. A meter stick is 100 centimeters. A measuring tape can bend around things.",
      "A centimeter is tiny, about as wide as your fingernail. An inch is a bit bigger, about the top part of your thumb. A meter is about one big step.",
      "Smaller units give bigger numbers. A pencil might be 6 inches, or about 15 centimeters. Same pencil! Centimeters are smaller, so it takes more of them.",
      "To measure, line up the end of the object with the 0 on the ruler. Then read the number at the other end. We can compare lengths too. A 9 inch stick is 4 inches longer than a 5 inch stick.",
      "Graphs help us see numbers. A line plot puts an X above each length on a number line. A bar graph uses bars to show how many are in each group.",
    ].join("\n\n"),
    keyIdeas: [
      "📏 12 inches = 1 foot. 100 centimeters = 1 meter.",
      "Start at 0 when you measure.",
      "Smaller units give bigger numbers for the same object.",
      "📊 Line plots and bar graphs help us compare.",
    ],
    hook: {
      text: "The mill's water wheel is broken. The miller needs a new board. How long should it be? Let's measure!",
    },
    teach: [
      {
        title: "Tools and Units",
        teach:
          "To measure, we need the right tool. A ruler is 12 inches long. That's one foot. A yardstick is 3 feet long. A meter stick is 100 centimeters. A measuring tape can bend around a tree! Start at zero. Line up the end of the thing with the 0. Then read the number at the other end. Use a ruler for a crayon. Use a measuring tape for a room.",
        visual: {
          type: "flip",
          cards: [
            { front: "Inch", back: "About the top part of your thumb 👍" },
            { front: "Foot", back: "12 inches, one whole ruler 📏" },
            { front: "Centimeter", back: "About as wide as a fingernail 🤏" },
            { front: "Meter", back: "100 centimeters, about one big step 🚶" },
          ],
        },
        probe: {
          type: "match",
          prompt: "Match each thing to the best tool.",
          pairs: [
            { left: "🖍️ a crayon", right: "Ruler 📏" },
            { left: "🌳 around a tree trunk", right: "Measuring tape (it bends)" },
            { left: "🚪 how tall a door is", right: "Yardstick or meter stick" },
          ],
          hint: "Small things get a small tool. Round things need a tool that bends.",
          seconds: 40,
        },
        think: {
          q: "A ruler is how many inches long?",
          choices: ["10", "12", "100"],
          answer: 1,
          why: "A ruler is one foot, and a foot is 12 inches.",
          hints: ["10 is close, but a ruler is one foot long.", "", "100 is how many centimeters are in a meter."],
        },
        approaches: {
          analogy: "Picking a measuring tool is like picking a spoon or a shovel. A tiny spoon for sugar, a big shovel for dirt. Small tool for small things, big tool for big things.",
          example: "To measure a crayon, put its end at the 0 on a ruler. The other end lines up with 4. The crayon is 4 inches long.",
          simpler: {
            q: "Where do you start when you measure with a ruler?",
            choices: ["At 0", "At 5", "In the middle"],
            answer: 0,
            why: "Line up the end of the object with 0.",
            hints: ["", "Starting at 5 makes it look 5 too long.", "Start at one end: line it up with 0."],
          },
        },
      },
      {
        title: "Estimate and Compare",
        teach:
          "An estimate is a smart guess. Use what you know. A paper clip is about 1 inch long. A big step is about 1 meter. Smaller units give bigger numbers. A book is 10 inches long. That's about 25 centimeters. Same book! Centimeters are smaller, so it takes more. We can compare lengths too. A 9 inch stick and a 5 inch stick. 9 - 5 = 4. The first stick is 4 inches longer.",
        visual: {
          type: "compare",
          left: { title: "Inches (bigger units)", points: ["Book: about 10 inches", "Pencil: about 6 inches", "Fewer units"] },
          right: { title: "Centimeters (smaller units)", points: ["Book: about 25 centimeters", "Pencil: about 15 centimeters", "More units"] },
        },
        probe: {
          type: "number",
          prompt: "A green ribbon is 17 inches long 🎀. A red ribbon is 9 inches long. How much longer is the green ribbon?",
          answer: 8,
          unit: "inches",
          hint: "How much longer means subtract: 17 - 9.",
          mistakes: [{ match: "26", coach: "We want how much longer, so subtract. Don't add." }],
          seconds: 30,
        },
        think: {
          q: "A table is 2 meters long. About how many centimeters is that?",
          choices: ["2", "20", "200"],
          answer: 2,
          why: "Each meter is 100 centimeters, so 2 meters is 200 centimeters.",
          hints: ["Centimeters are smaller, so there are more of them.", "Each meter is 100 centimeters, not 10.", ""],
        },
        approaches: {
          analogy: "Measuring with smaller units is like paying with pennies instead of dollars. It's the same amount, but you need a lot more pennies.",
          example: "A shoe is 7 inches long and a sandal is 5 inches long. 7 - 5 = 2. The shoe is 2 inches longer.",
          simpler: {
            q: "Which is longer: 1 inch or 1 centimeter?",
            choices: ["1 inch", "1 centimeter", "The same"],
            answer: 0,
            why: "An inch is a bit longer than 2 centimeters.",
            hints: ["", "A centimeter is smaller, about the width of a fingernail.", "They are different units, so they're not the same size."],
          },
        },
      },
      {
        title: "Line Plots and Bar Graphs",
        teach:
          "Graphs help us see numbers. A line plot shows lengths. Measure five sticks. Put an X above each length on a number line. The tallest stack of X's is the most common length. A bar graph shows groups. Kids vote for their favorite fruit. Apples get 6 votes. Pears get 2 votes. The apple bar is taller. Apples have 4 more votes!",
        visual: {
          type: "hotspots",
          title: "Favorite fruit (a bar graph)",
          center: "📊",
          spots: [
            { label: "Apples: 6", icon: "🍎", detail: "The tallest bar: 6 votes." },
            { label: "Bananas: 4", icon: "🍌", detail: "4 votes." },
            { label: "Pears: 2", icon: "🍐", detail: "The shortest bar: 2 votes. Apples have 4 more than pears." },
          ],
        },
        probe: {
          type: "place",
          prompt: "Make a line plot! Put an X on the line for each stick.",
          min: 0,
          max: 10,
          step: 1,
          tolerance: 0,
          items: [
            { label: "🪵 3 inches", value: 3 },
            { label: "🪵 5 inches", value: 5 },
            { label: "🪵 8 inches", value: 8 },
          ],
          hint: "Find each number on the line and drop the X right there.",
          seconds: 30,
        },
        think: {
          q: "On a line plot, 3 X's are above 5 inches and 1 X is above 4 inches. Which length is most common?",
          choices: ["4 inches", "5 inches", "3 inches"],
          answer: 1,
          why: "The tallest stack, 3 X's, is above 5 inches.",
          hints: ["Only 1 X is above 4. Look for the tallest stack.", "", "3 is how many X's, not the length."],
        },
        approaches: {
          analogy: "A line plot is like stacking blocks above numbers. The tallest stack shows the length that happened most.",
          example: "Kids measured 4 leaves: 3, 4, 4 and 6 inches. Put one X above 3, two X's above 4, and one X above 6. The most common length is 4 inches.",
          simpler: {
            q: "On a ruler, what number comes right after 5?",
            choices: ["4", "6", "10"],
            answer: 1,
            why: "The marks go 4, 5, 6, in order.",
            hints: ["4 comes before 5.", "", "10 is too far. Just one more."],
          },
        },
      },
    ],
    activity: {
      type: "sequence",
      prompt: "Put the measuring steps in order.",
      steps: [
        "Pick the right tool",
        "Line up the end of the object with 0",
        "Keep the object straight along the ruler",
        "Read the number at the other end",
        "Write the length with its unit, like 6 inches",
      ],
    },
    explain: {
      prompt: "Why does a pencil measure more centimeters than inches? Explain it in your own words.",
      keyPoints: ["Centimeters are smaller than inches", "Smaller units fit more times", "So the number of centimeters is bigger", "The pencil is the same length either way"],
    },
    mastery: [
      {
        type: "number",
        prompt: "A worm 🪱 is 6 centimeters long. A toy snake 🐍 is 45 centimeters long. How much longer is the toy snake?",
        answer: 39,
        unit: "centimeters",
        hint: "Subtract the shorter length from the longer one.",
        mistakes: [{ match: "51", coach: "How much longer means subtract: 45 - 6." }],
        seconds: 40,
      },
      {
        type: "match",
        prompt: "Match each thing to a good estimate.",
        pairs: [
          { left: "📎 a paper clip", right: "about 1 inch" },
          { left: "📏 a ruler", right: "1 foot" },
          { left: "🚪 a door's height", right: "about 2 meters" },
          { left: "✏️ a new pencil", right: "about 19 centimeters" },
        ],
        hint: "A paper clip is tiny. A door is taller than a grown-up.",
        seconds: 45,
      },
      {
        type: "sort",
        prompt: "Which unit fits best?",
        buckets: ["Inches or centimeters (small things)", "Feet or meters (big things)"],
        items: [
          { text: "🐜 an ant", bucket: 0 },
          { text: "🏠 a house", bucket: 1 },
          { text: "🍌 a banana", bucket: 0 },
          { text: "🏊 a swimming pool", bucket: 1 },
          { text: "🔑 a key", bucket: 0 },
          { text: "🚌 a school bus", bucket: 1 },
        ],
        hint: "Could it fit on a ruler? Then use small units.",
        seconds: 40,
      },
      {
        type: "place",
        prompt: "A plank is 20 inches long. Add 15 inches. Then add 10 more inches. Mark each length on the number line.",
        min: 0,
        max: 60,
        step: 5,
        tolerance: 0,
        items: [
          { label: "Start: 20 inches", value: 20 },
          { label: "After adding 15", value: 35 },
          { label: "After adding 10 more", value: 45 },
        ],
        hint: "Start at 20. Jump 15. Then jump 10 more.",
        seconds: 50,
      },
    ],
    check: [
      { q: "How many inches are in a foot?", choices: ["10", "100", "12"], answer: 2, why: "One foot is 12 inches, as long as a ruler." },
      { q: "Which is the best estimate for a door's height?", choices: ["2 centimeters", "2 meters", "2 inches"], answer: 1, why: "A door is taller than a grown-up, about 2 meters." },
      { q: "A pencil is 7 inches. A crayon is 3 inches. How much longer is the pencil?", choices: ["4 inches", "10 inches", "3 inches"], answer: 0, why: "7 - 3 = 4 inches." },
      { q: "Why does a desk measure more centimeters than inches?", choices: ["The desk grew", "Centimeters are bigger", "Centimeters are smaller"], answer: 2, why: "Smaller units fit more times, so the number is bigger." },
    ],
    task: {
      kind: "lab",
      prompt: "With a grown-up, measure 5 things at home with a ruler, like a spoon, a book, a shoe, a toothbrush and a cup. Guess each length first, then measure to the nearest inch. Make a line plot with an X for each length.",
      rubric: ["Made a guess before measuring", "Lined up each object with 0", "Wrote each length with its unit", "Drew a line plot with one X for each object"],
    },
  },

  // 8. Time to 5 minutes, and money
  {
    id: "math-2.time-money",
    title: "Clocks and Coins",
    minutes: 20,
    stage: "grammar",
    standards: ["2.MD.C.7", "2.MD.C.8"],
    read: [
      "A clock has two hands. The short hand points to the hour. The long hand points to the minutes. When the long hand points to 12, it's o'clock. Each number is 5 minutes for the long hand, so count by 5s! If the long hand points to 4, it's 20 minutes past the hour. A digital clock shows the time in numbers, like 3:20.",
      "AM means the morning, from midnight to noon. PM means the afternoon and evening, from noon to midnight. You eat breakfast in the AM and dinner in the PM.",
      "Coins have different values. A penny is 1 cent. A nickel is 5 cents. A dime is 10 cents. A quarter is 25 cents. A dollar is 100 cents. To count coins, start with the biggest. Two quarters and a dime is 25, 50, 60. That's 60 cents! We write 60¢.",
    ].join("\n\n"),
    keyIdeas: [
      "🕒 Short hand = hour. Long hand = minutes. Count by 5s.",
      "🌅 AM is morning. 🌙 PM is afternoon and evening.",
      "🪙 Penny 1¢, nickel 5¢, dime 10¢, quarter 25¢, dollar 100¢.",
      "Count the biggest coins first.",
    ],
    hook: {
      text: "The Riverbend market opens at 8 o'clock in the morning. Shoppers bring coins and dollar bills. To shop, you need to read the clock and count your money!",
    },
    teach: [
      {
        title: "Reading the Clock",
        teach:
          "A clock has two hands. The short hand tells the hour. The long hand tells the minutes. Each number is 5 minutes for the long hand. So we count by 5s! The long hand on 1 means 5 minutes. On 2, it means 10 minutes. On 6, it means 30 minutes, or half past. If the short hand is just past 3 and the long hand is on 4, it's 3:20.",
        visual: {
          type: "flip",
          cards: [
            { front: "Long hand on 12", back: "o'clock (:00) 🕒" },
            { front: "Long hand on 3", back: "15 minutes (:15)" },
            { front: "Long hand on 6", back: "30 minutes, half past (:30) 🕞" },
            { front: "Long hand on 9", back: "45 minutes (:45)" },
            { front: "Long hand on 11", back: "55 minutes (:55)" },
          ],
        },
        probe: {
          type: "match",
          prompt: "Match where the long hand points to the minutes.",
          pairs: [
            { left: "Long hand on 2", right: ":10" },
            { left: "Long hand on 5", right: ":25" },
            { left: "Long hand on 8", right: ":40" },
            { left: "Long hand on 10", right: ":50" },
          ],
          hint: "Count by 5s for each number: 5, 10, 15 ...",
          seconds: 40,
        },
        think: {
          q: "The short hand is just past 7. The long hand is on 3. What time is it?",
          choices: ["7:03", "7:15", "3:35"],
          answer: 1,
          why: "The long hand on 3 means 3 jumps of 5: 15 minutes. So 7:15.",
          hints: ["The long hand on 3 means 3 jumps of 5 minutes, not 3 minutes.", "", "The short hand tells the hour, and it's past 7."],
        },
        approaches: {
          analogy: "The long hand is like a runner who goes all the way around the track every hour. The short hand is a slow walker who moves just one number each hour.",
          example: "The short hand is between 9 and 10. The long hand is on 7. Count by 5s: 5, 10, 15, 20, 25, 30, 35. It's 9:35.",
          simpler: {
            q: "Count by 5s: 5, 10, 15, ___?",
            choices: ["16", "20", "25"],
            answer: 1,
            why: "15 + 5 = 20.",
            hints: ["That's counting by 1s. Jump by 5.", "", "That's two jumps. Just one jump of 5."],
          },
        },
      },
      {
        title: "Morning or Evening?",
        teach:
          "The short hand goes around the clock twice each day. So 7 o'clock could be morning or evening! We use AM and PM to tell them apart. AM is from midnight to noon. That's the morning. PM is from noon to midnight. That's the afternoon and evening. You wake up at 7 AM. You eat dinner at 6 PM. Noon is 12 PM, time for lunch!",
        visual: {
          type: "sort",
          prompt: "AM or PM?",
          buckets: ["AM (morning) 🌅", "PM (afternoon or evening) 🌙"],
          items: [
            { text: "🥣 eating breakfast", bucket: 0 },
            { text: "🌙 looking at the stars", bucket: 1 },
            { text: "🐓 the rooster crows at sunrise", bucket: 0 },
            { text: "🍝 eating dinner", bucket: 1 },
            { text: "🛁 a bath before bed", bucket: 1 },
          ],
        },
        probe: {
          type: "cloze",
          text: "School starts at 8:30 {0}. We eat dinner at 6:00 {1}.",
          blanks: [{ answers: ["AM", "a.m."] }, { answers: ["PM", "p.m."] }],
          bank: ["AM", "PM", "noon"],
          hint: "AM is the morning. PM is the afternoon and evening.",
          seconds: 30,
        },
        think: {
          q: "Which time is in the afternoon?",
          choices: ["9:00 AM", "3:00 PM", "6:00 AM"],
          answer: 1,
          why: "PM is after noon, so 3:00 PM is in the afternoon.",
          hints: ["AM is the morning.", "", "6:00 AM is early morning, around sunrise."],
        },
        approaches: {
          analogy: "AM and PM are like the two halves of a sandwich: the morning half and the afternoon-and-evening half, with noon right in the middle.",
          example: "You wake up at 7 o'clock. It's morning, so it's 7:00 AM. You go to bed at 8 o'clock at night, so it's 8:00 PM.",
          simpler: {
            q: "When do people usually eat breakfast?",
            choices: ["In the morning", "At night", "At midnight"],
            answer: 0,
            why: "Breakfast is the first meal of the day, in the morning.",
            hints: ["", "Night is for dinner and bedtime.", "Midnight is when most people are asleep."],
          },
        },
      },
      {
        title: "Counting Coins and Bills",
        teach:
          "Let's count money! A penny is 1 cent. A nickel is 5 cents. A dime is 10 cents. A quarter is 25 cents. A dollar bill is 100 cents. Count the biggest coins first. Two quarters and one dime. 25, 50, 60. That's 60 cents! We write it with a cent sign: 60¢. For dollars we use a dollar sign, like $5.",
        visual: {
          type: "flip",
          cards: [
            { front: "Penny", back: "1¢" },
            { front: "Nickel", back: "5¢" },
            { front: "Dime", back: "10¢" },
            { front: "Quarter", back: "25¢" },
            { front: "Dollar bill 💵", back: "$1 = 100¢" },
          ],
        },
        probe: {
          type: "number",
          prompt: "You have 1 quarter, 2 dimes and 3 pennies. How many cents is that?",
          answer: 48,
          unit: "¢",
          hint: "Start with the quarter: 25. Count on the dimes by 10s, then the pennies by 1s.",
          mistakes: [{ match: "6", coach: "That's how many coins. Count what each coin is worth." }],
          seconds: 45,
        },
        think: {
          q: "How much are 3 dimes worth?",
          choices: ["3¢", "30¢", "13¢"],
          answer: 1,
          why: "A dime is 10¢. Count by 10s: 10, 20, 30.",
          hints: ["A dime is worth 10 cents, not 1.", "", "Count by 10s: 10, 20, 30."],
        },
        approaches: {
          analogy: "Counting coins is like skip counting with different jumps: big jumps of 25 for quarters, 10 for dimes, 5 for nickels, then tiny steps of 1 for pennies.",
          example: "2 quarters, 1 nickel and 2 pennies: 25, 50, then 55, then 56, 57. That's 57¢.",
          simpler: {
            q: "How much is a nickel worth?",
            choices: ["1¢", "5¢", "10¢"],
            answer: 1,
            why: "A nickel is worth 5 cents.",
            hints: ["That's a penny.", "", "That's a dime, the small thin coin."],
          },
        },
      },
    ],
    activity: {
      type: "sequence",
      prompt: "Put the day in order, from morning to night.",
      steps: ["7:00 AM: wake up 🌅", "8:30 AM: start school ✏️", "12:00 PM: eat lunch 🥪", "3:15 PM: play outside ⚽", "6:00 PM: eat dinner 🍝", "8:00 PM: go to bed 🛏️"],
    },
    explain: {
      prompt: "How do you count 2 quarters, 1 dime and 3 pennies? Explain how you count.",
      keyPoints: ["Start with the biggest coins", "Count the quarters: 25, 50", "Add the dime: 60", "Add the pennies: 61, 62, 63 cents"],
    },
    mastery: [
      {
        type: "number",
        prompt: "It is 4:35. Which number on the clock does the long hand point to?",
        answer: 7,
        hint: "Count by 5s until you reach 35: 5, 10, 15 ...",
        mistakes: [{ match: "35", coach: "The clock only has the numbers 1 to 12. Count by 5s: which number is 35 minutes?" }],
        seconds: 40,
      },
      {
        type: "cloze",
        text: "A toy costs 75¢. You pay with a dollar bill, which is 100¢. Your change is {0}¢.",
        blanks: [{ answers: ["25"] }],
        bank: ["25", "75", "35", "15"],
        hint: "Count up from 75 to 100.",
        seconds: 40,
      },
      {
        type: "match",
        prompt: "Match the coins to the amount.",
        pairs: [
          { left: "1 quarter and 1 nickel", right: "30¢" },
          { left: "2 dimes and 2 pennies", right: "22¢" },
          { left: "3 quarters", right: "75¢" },
          { left: "4 nickels", right: "20¢" },
        ],
        hint: "Count the biggest coin first, then count on.",
        seconds: 50,
      },
      {
        type: "sort",
        prompt: "AM or PM?",
        buckets: ["AM", "PM"],
        items: [
          { text: "🌅 sunrise", bucket: 0 },
          { text: "🍲 supper", bucket: 1 },
          { text: "🥞 breakfast", bucket: 0 },
          { text: "✨ a starry sky", bucket: 1 },
        ],
        hint: "AM is the morning. PM is the afternoon and evening.",
        seconds: 30,
      },
    ],
    check: [
      { q: "The long hand points to 9. How many minutes past the hour is it?", choices: ["9", "45", "30"], answer: 1, why: "Count by 5s nine times: 45 minutes." },
      { q: "How much is 1 quarter and 1 dime?", choices: ["35¢", "26¢", "11¢"], answer: 0, why: "25 + 10 = 35¢." },
      { q: "Which coin is worth the most?", choices: ["Dime", "Nickel", "Quarter"], answer: 2, why: "A quarter is 25¢, more than a dime (10¢) or a nickel (5¢)." },
      { q: "Dinner is at 6 o'clock in the evening. How do we write it?", choices: ["6:00 AM", "6:00 PM", "6:00 noon"], answer: 1, why: "Evening is after noon, so it's PM." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, look at a clock with hands 3 times today. Say each time to the nearest 5 minutes, with AM or PM. Then count a small handful of real coins and say how many cents it is.",
      rubric: ["Read the clock to the nearest 5 minutes", "Said AM or PM correctly", "Counted coins starting with the biggest", "Wrote the amount with the ¢ sign"],
    },
  },

  // 9. Shapes, arrays and equal shares
  {
    id: "math-2.shapes",
    title: "Shapes, Arrays and Equal Shares",
    minutes: 20,
    stage: "rhetoric",
    standards: ["2.G.A.1", "2.G.A.2", "2.G.A.3", "2.OA.C.4"],
    read: [
      "Shapes have sides and angles. An angle is a corner where two sides meet. A triangle has 3 sides and 3 angles. A quadrilateral has 4 sides and 4 angles. Squares and rectangles are quadrilaterals. A pentagon has 5 sides. A hexagon has 6 sides. A cube is a solid shape with 6 square faces, all the same size.",
      "An array is things in rows and columns. 3 rows of 4 apples is 4 + 4 + 4 = 12 apples. We can split a rectangle into rows and columns of same-size squares, too. Then we count the squares.",
      "We can cut shapes into equal shares. Two equal shares are halves. Three equal shares are thirds. Four equal shares are fourths. A whole is 2 halves, 3 thirds or 4 fourths. Equal shares don't have to look the same, as long as they are the same size.",
    ].join("\n\n"),
    keyIdeas: [
      "🔺 Triangle 3 sides, 🟦 quadrilateral 4, pentagon 5, hexagon 6. 🎲 A cube has 6 square faces.",
      "An array is rows and columns: 3 rows of 4 = 4 + 4 + 4 = 12.",
      "🍕 Equal shares: halves, thirds and fourths.",
      "Equal shares are the same size, even if they look different.",
    ],
    hook: {
      text: "The Riverbend bridge needs new stones and tiles. Builders use triangles, squares and hexagons. Let's look at shapes like a builder!",
    },
    teach: [
      {
        title: "Sides and Angles",
        teach:
          "Let's count sides and angles. An angle is a corner. A triangle has 3 sides and 3 angles. A quadrilateral has 4 sides. Squares and rectangles are quadrilaterals. A pentagon has 5 sides. A hexagon has 6 sides, like a cell in a honeycomb. Some shapes are solid, like a cube. A cube has 6 square faces, all the same size. Think of a number cube!",
        visual: {
          type: "flip",
          cards: [
            { front: "Triangle 🔺", back: "3 sides, 3 angles" },
            { front: "Quadrilateral 🟦", back: "4 sides, 4 angles" },
            { front: "Pentagon", back: "5 sides, 5 angles" },
            { front: "Hexagon 🐝", back: "6 sides, 6 angles, like a honeycomb cell" },
            { front: "Cube 🎲", back: "A solid with 6 square faces" },
          ],
        },
        probe: {
          type: "match",
          prompt: "Match each shape to its number of sides.",
          pairs: [
            { left: "Triangle", right: "3 sides" },
            { left: "Quadrilateral", right: "4 sides" },
            { left: "Pentagon", right: "5 sides" },
            { left: "Hexagon", right: "6 sides" },
          ],
          hint: "Tri means 3, quad means 4, penta means 5, and hexa means 6.",
          seconds: 40,
        },
        think: {
          q: "A shape has 6 sides. What is it?",
          choices: ["Pentagon", "Hexagon", "Triangle"],
          answer: 1,
          why: "A hexagon has 6 sides and 6 angles.",
          hints: ["A pentagon has 5 sides, one fewer.", "", "A triangle has only 3 sides."],
        },
        approaches: {
          analogy: "Shape names are like counting words. Tri means three, like a tricycle with 3 wheels. Quad means four, and hexa means six.",
          example: "A yield sign is a triangle. Count its sides: 1, 2, 3. Count its corners: 1, 2, 3. Three sides and three angles!",
          simpler: {
            q: "How many sides does a triangle have?",
            choices: ["3", "4", "5"],
            answer: 0,
            why: "Tri means three: a triangle has 3 sides.",
            hints: ["", "4 sides is a quadrilateral, like a square.", "5 sides is a pentagon."],
          },
        },
      },
      {
        title: "Arrays and Rows of Squares",
        teach:
          "An array has rows and columns. Rows go across. Columns go up and down. Look at 3 rows of 4 apples. Add the rows. 4 + 4 + 4 = 12. That's 12 apples! We can cut a rectangle into rows and columns of same-size squares. Try 2 rows of 5 squares. 5 + 5 = 10 squares. Arrays help us count fast.",
        visual: {
          type: "compare",
          left: { title: "3 rows of 4", points: ["🍎🍎🍎🍎", "🍎🍎🍎🍎", "🍎🍎🍎🍎", "4 + 4 + 4 = 12"] },
          right: { title: "2 rows of 5", points: ["🟦🟦🟦🟦🟦", "🟦🟦🟦🟦🟦", "5 + 5 = 10"] },
        },
        probe: {
          type: "build",
          prompt: "🌷🌷🌷🌷🌷 / 🌷🌷🌷🌷🌷 / 🌷🌷🌷🌷🌷. Build the addition for this array.",
          tiles: ["Row 1: 5", "+ Row 2: 5", "+ Row 3: 5", "= 15"],
          distractors: ["+ Row 4: 5", "= 10"],
          hint: "There are 3 rows with 5 flowers in each row.",
          seconds: 40,
        },
        think: {
          q: "4 rows of 3 stars. How many stars?",
          choices: ["7", "12", "10"],
          answer: 1,
          why: "3 + 3 + 3 + 3 = 12.",
          hints: ["That's 4 + 3. Add a 3 for each of the 4 rows.", "", "Count again: 3 + 3 + 3 + 3."],
        },
        approaches: {
          analogy: "An array is like an egg carton. Neat rows and columns let you count by rows instead of one by one.",
          example: "A garden has 3 rows of 5 carrots. Add the rows: 5 + 5 + 5 = 15 carrots.",
          simpler: {
            q: "2 rows of 2 cookies. How many cookies?",
            choices: ["3", "4", "6"],
            answer: 1,
            why: "2 + 2 = 4.",
            hints: ["Count again: 2 in one row, 2 in the other.", "", "That's too many. Just 2 + 2."],
          },
        },
      },
      {
        title: "Equal Shares",
        teach:
          "Sharing a pie fairly means equal shares. Every piece is the same size. Cut a pie into 2 equal shares. Each is a half. Cut it into 3 equal shares. Each is a third. Cut it into 4 equal shares. Each is a fourth. More shares means smaller pieces! Two halves make a whole. So do 3 thirds, or 4 fourths. Halves of a square can be two rectangles or two triangles. Different shapes, same size!",
        visual: {
          type: "compare",
          left: { title: "Equal shares ✅", points: ["Every piece is the same size", "2 shares = halves", "3 shares = thirds", "4 shares = fourths"] },
          right: { title: "Not equal ❌", points: ["One piece is bigger", "That's not fair sharing!"] },
        },
        probe: {
          type: "cloze",
          text: "A pizza 🍕 is cut into 4 equal shares. Each share is one {0}. The whole pizza is {1} fourths.",
          blanks: [{ answers: ["fourth", "quarter"] }, { answers: ["4", "four"] }],
          bank: ["fourth", "half", "third", "4", "2"],
          hint: "4 equal shares are fourths. How many fourths make the whole?",
          seconds: 40,
        },
        think: {
          q: "Which is bigger: a half or a fourth of the same pie?",
          choices: ["A half", "A fourth", "They're the same"],
          answer: 0,
          why: "Fewer shares means bigger pieces. A half is bigger.",
          hints: ["", "More shares means smaller pieces. A fourth is smaller.", "Cutting into 2 or into 4 gives different sizes."],
        },
        approaches: {
          analogy: "Equal shares are like sharing a sandwich with friends. If everyone's piece is the same size, it's fair. More friends means smaller pieces.",
          example: "Cut a square sandwich from corner to corner. You get 2 triangles of the same size. Each is a half. Cut it straight down the middle instead: 2 rectangles. Each is a half too!",
          simpler: {
            q: "A cookie is cut into 2 equal pieces. What is each piece called?",
            choices: ["A half", "A third", "A fourth"],
            answer: 0,
            why: "2 equal shares are halves.",
            hints: ["", "Thirds come from 3 equal pieces.", "Fourths come from 4 equal pieces."],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "Sort the shapes by their sides.",
      buckets: ["3 sides", "4 sides", "5 or 6 sides"],
      items: [
        { text: "🔺 triangle", bucket: 0 },
        { text: "🟥 square", bucket: 1 },
        { text: "🚪 the outline of a door (a rectangle)", bucket: 1 },
        { text: "pentagon", bucket: 2 },
        { text: "🐝 a honeycomb cell (a hexagon)", bucket: 2 },
        { text: "⚠️ a warning sign (a triangle)", bucket: 0 },
        { text: "🔷 a diamond (a quadrilateral)", bucket: 1 },
      ],
    },
    explain: {
      prompt: "How do you know a shape is cut into fourths? Explain with a pizza or a sandwich.",
      keyPoints: ["There are 4 shares", "All 4 shares are the same size", "Each share is one fourth", "4 fourths make a whole"],
    },
    mastery: [
      {
        type: "match",
        prompt: "Match each clue to the shape.",
        pairs: [
          { left: "3 sides, 3 angles", right: "Triangle" },
          { left: "4 sides, 4 square corners", right: "Rectangle" },
          { left: "6 sides, 6 angles", right: "Hexagon" },
          { left: "6 square faces", right: "Cube" },
        ],
        hint: "Count the sides. A cube is a solid shape, not a flat one.",
        seconds: 45,
      },
      {
        type: "number",
        prompt: "A rectangle is cut into 3 rows of 4 same-size squares. How many squares in all?",
        answer: 12,
        hint: "Add 4 for each row: 4 + 4 + 4.",
        mistakes: [{ match: "7", coach: "That's 3 + 4. Add 4 for each of the 3 rows." }],
        seconds: 30,
      },
      {
        type: "sort",
        prompt: "Equal shares or not?",
        buckets: ["Equal shares", "Not equal"],
        items: [
          { text: "🍕 a pizza cut into 4 same-size slices", bucket: 0 },
          { text: "🥪 a sandwich cut into one big piece and one tiny piece", bucket: 1 },
          { text: "🍫 a chocolate bar broken into 3 same-size pieces", bucket: 0 },
          { text: "🥧 a pie cut into 2 pieces that aren't the same size", bucket: 1 },
        ],
        hint: "Equal shares must all be the same size.",
        seconds: 40,
      },
      {
        type: "cloze",
        text: "Cut a cake into 3 equal shares. Each share is one {0}. Cut it into 2 equal shares. Each share is one {1}.",
        blanks: [{ answers: ["third"] }, { answers: ["half"] }],
        bank: ["third", "half", "fourth", "whole"],
        hint: "3 equal shares are thirds. 2 equal shares are halves.",
        seconds: 35,
      },
    ],
    check: [
      { q: "How many angles does a pentagon have?", choices: ["4", "6", "5"], answer: 2, why: "A pentagon has 5 sides and 5 angles." },
      { q: "4 rows of 5 chairs. How many chairs?", choices: ["9", "20", "15"], answer: 1, why: "5 + 5 + 5 + 5 = 20." },
      { q: "A sandwich is cut into 4 equal shares. Each share is a...", choices: ["fourth", "third", "half"], answer: 0, why: "4 equal shares are fourths." },
      { q: "Which shape has 4 sides?", choices: ["Triangle", "Hexagon", "Quadrilateral"], answer: 2, why: "Quad means four. A quadrilateral has 4 sides." },
    ],
    task: {
      kind: "project",
      prompt: "With a grown-up, go on a shape hunt at home. Find a triangle, a quadrilateral, a hexagon or pentagon, and a cube. Then fold a sheet of paper into halves, then into fourths, and color one fourth.",
      rubric: ["Found and named at least 3 shapes", "Counted the sides of each flat shape", "Folded the paper into equal halves and fourths", "Colored exactly one fourth"],
    },
  },
]);
