import { k5Course } from "./base";

/**
 * sci-1: Grade 1 science (NGSS), taught by Dr. Carver in Whisperwood Forest,
 * where the fog stole the songbirds' songs. Everything is read aloud.
 */
export const sci1 = k5Course("sci", 1, [
  // 1. Sound and vibration (1-PS4-1)
  {
    id: "sci-1.sound",
    title: "Sounds Are Shakes",
    minutes: 15,
    stage: "grammar",
    standards: ["1-PS4-1"],
    read: [
      "Listen. Do you hear a bird? A car? A voice? Every sound starts with a shake. Scientists call a fast shake a vibration.",
      "Put your hand on your throat and hum. Do you feel a buzz? That buzz is your throat shaking. Pluck a rubber band. It wiggles fast, and you hear a twang. Tap a drum. The top shakes, and you hear a boom.",
      "Big shakes make loud sounds. Small shakes make soft sounds. When the shaking stops, the sound stops too.",
      "Sound can also make things shake. Stretch plastic wrap over a bowl. Sprinkle a little rice on top. Bang a pot right next to it. The rice hops! The sound moved through the air and shook the plastic.",
      "So remember: no shake, no sound. And sound can make things shake, too.",
    ].join("\n\n"),
    keyIdeas: [
      "Every sound is made by something shaking. A fast shake is called a vibration.",
      "Big shakes make loud sounds. Small shakes make soft sounds.",
      "Sound can make other things shake, too.",
    ],
    hook: {
      text: "Shh. Listen to Whisperwood Forest. The fog took the songbirds' songs! To get them back, we need to know what a sound really is. What do you notice when you hum?",
    },
    teach: [
      {
        title: "Every Sound Is a Shake",
        teach:
          "Put your hand on your throat. Now hum. Do you feel a buzz? Your throat is shaking! Every sound starts with a shake. A fast shake is called a vibration. Pluck a guitar string. It shakes, and you hear a twang. Tap a drum. Its top shakes, and you hear a boom. A bell shakes when it rings.",
        visual: {
          type: "hotspots",
          title: "What shakes?",
          center: "Sound",
          spots: [
            { label: "Your voice", icon: "🗣️", detail: "Your throat shakes when you talk, sing or hum. Feel it with your hand!" },
            { label: "Guitar", icon: "🎸", detail: "The strings shake back and forth very fast." },
            { label: "Drum", icon: "🥁", detail: "The top of the drum shakes when you tap it." },
            { label: "Bell", icon: "🔔", detail: "The metal of the bell shakes when it rings." },
          ],
        },
        probe: {
          type: "match",
          prompt: "What shakes to make the sound? Match each one.",
          pairs: [
            { left: "🎸 guitar", right: "the strings" },
            { left: "🥁 drum", right: "the top" },
            { left: "🗣️ singing", right: "your throat" },
            { left: "🔔 bell", right: "the metal" },
          ],
          hint: "Find the part you touch or hit. That part shakes.",
          mistakes: [{ match: "drum and the strings", coach: "A drum has no strings. You tap its top, and the top shakes." }],
          seconds: 40,
        },
        think: {
          q: "What makes every sound?",
          choices: ["Something shaking", "Something cold", "Something bright"],
          answer: 0,
          why: "Every sound starts with something shaking, or vibrating.",
          hints: ["", "Cold things can be quiet. A cold rock makes no sound until it shakes.", "Bright things can be quiet. A lamp makes light, not sound."],
        },
        approaches: {
          analogy: "A sound is like a wiggle you can hear. When something wiggles fast, it pushes the air, and the push reaches your ear.",
          example: "Stretch a rubber band around a box. Pluck it. Look closely: the band blurs because it shakes so fast. Twang! Hold it still, and the sound stops.",
          simpler: {
            q: "Hum and touch your throat. What do you feel?",
            choices: ["Nothing at all", "A buzzy shake"],
            answer: 1,
            why: "Your throat shakes when you hum. That shake makes the sound.",
            hints: ["Try it again and press gently. Humming makes your throat buzz.", ""],
          },
        },
      },
      {
        title: "Loud and Soft",
        teach:
          "Tap a drum softly. The top makes a small shake. You hear a soft sound. Now bang it hard. The top makes a big shake. You hear a loud boom! Big shakes make loud sounds. Small shakes make soft sounds. Now ring a bell, then touch it. The shaking stops. What happens? The sound stops too!",
        visual: {
          type: "compare",
          left: { title: "Big shake 📢", points: ["A hard bang on a drum", "A shout", "A loud sound"] },
          right: { title: "Small shake 🤫", points: ["A soft tap on a drum", "A whisper", "A soft sound"] },
        },
        probe: {
          type: "sort",
          prompt: "Big shake or small shake? Sort each sound.",
          buckets: ["Big shake: loud 📢", "Small shake: soft 🤫"],
          items: [
            { text: "🥁 a hard bang", bucket: 0 },
            { text: "🗣️ a shout", bucket: 0 },
            { text: "🎸 a hard pluck", bucket: 0 },
            { text: "🥁 a soft tap", bucket: 1 },
            { text: "🤫 a whisper", bucket: 1 },
            { text: "🎸 a gentle pluck", bucket: 1 },
          ],
          hint: "Loud sounds come from big shakes. Soft sounds come from small shakes.",
          mistakes: [{ match: "whisper as big shake", coach: "A whisper is soft and quiet, so it comes from a small shake." }],
          seconds: 45,
        },
        think: {
          q: "You hold a ringing bell still. What happens?",
          choices: ["It rings louder", "Nothing changes", "The sound stops"],
          answer: 2,
          why: "When the shaking stops, the sound stops too.",
          hints: ["Holding it makes the shaking stop, not grow bigger.", "Your hand stops the bell from shaking. That changes the sound.", ""],
        },
        approaches: {
          analogy: "Shakes are like waves in a bathtub. A big splash makes big waves. A tiny poke makes tiny waves. Big shakes make loud sounds.",
          example: "Pluck a rubber band gently: a small wiggle and a soft twang. Pull it farther and let go: a big wiggle and a louder twang.",
          simpler: {
            q: "Which is louder?",
            choices: ["A whisper", "A shout"],
            answer: 1,
            why: "A shout comes from a big shake, so it is louder.",
            hints: ["A whisper is very quiet. It comes from a small shake.", ""],
          },
        },
      },
      {
        title: "Sound Makes Things Shake",
        teach:
          "Here is a fun trick. Stretch plastic wrap over a bowl. Sprinkle a little rice on top. Now bang a pot right next to the bowl. Look! The rice hops. Why? The sound moved through the air. It made the plastic shake. So shakes make sound, and sound makes things shake. What do you notice?",
        visual: {
          type: "flip",
          cards: [
            { front: "🥣 Bowl", back: "Stretch plastic wrap tight over the top, like a drum." },
            { front: "🍚 Rice", back: "Sprinkle a little on the plastic. Watch it closely." },
            { front: "🍳 Pot", back: "Bang it with a spoon right next to the bowl." },
            { front: "🦘 Hop!", back: "The sound shakes the plastic, and the rice jumps." },
          ],
        },
        probe: {
          type: "sequence",
          prompt: "Put the rice trick in order.",
          steps: ["🥣 Stretch plastic wrap over a bowl", "🍚 Sprinkle rice on top", "🍳 Bang a pot next to the bowl", "🦘 The rice hops!"],
          hint: "First make the drum, then add rice. Make the sound before the rice can hop.",
          mistakes: [{ match: "rice hops first", coach: "The rice can't hop until a sound shakes the plastic." }],
          seconds: 40,
        },
        think: {
          q: "Why did the rice hop?",
          choices: ["The wind blew it", "The sound shook the plastic", "The rice was hungry"],
          answer: 1,
          why: "The sound moved through the air and made the plastic shake.",
          hints: ["There was no wind. The bang of the pot did it.", "", "Rice is not alive. Something shook it."],
        },
        approaches: {
          analogy: "Sound is like a push you can't see. It travels through the air and gives a little push to whatever it reaches.",
          example: "Hold a balloon gently while someone sings close to it. You can feel the balloon buzz. Their voice made the balloon shake.",
          simpler: {
            q: "Can a sound make something shake?",
            choices: ["Yes", "No, never"],
            answer: 0,
            why: "Sound travels through the air and makes things shake, like the rice on the plastic.",
            hints: ["", "Remember the rice. The bang of the pot made it hop."],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "Shaking or still? Sort them.",
      buckets: ["Shaking: makes a sound 🔊", "Still: quiet 🔇"],
      items: [
        { text: "🔔 a ringing bell", bucket: 0 },
        { text: "🐝 a bee's buzzing wings", bucket: 0 },
        { text: "🎸 a plucked string", bucket: 0 },
        { text: "🗣️ your throat when you hum", bucket: 0 },
        { text: "🪨 a rock on the ground", bucket: 1 },
        { text: "🥁 a drum no one taps", bucket: 1 },
        { text: "🔕 a bell held still", bucket: 1 },
      ],
    },
    explain: {
      prompt: "Tell me how a drum makes a sound. How do you make it loud or soft?",
      keyPoints: ["The drum shakes or vibrates", "Big shakes make loud sounds", "Small shakes make soft sounds"],
    },
    mastery: [
      {
        type: "cloze",
        text: "Every sound starts with a {0}. A fast shake is called a {1}. Big shakes make {2} sounds.",
        blanks: [{ answers: ["shake"] }, { answers: ["vibration"] }, { answers: ["loud"] }],
        bank: ["shake", "vibration", "loud", "soft", "light", "color"],
        hint: "Think of your humming throat. It shakes, and big shakes are loud.",
        mistakes: [{ match: "soft", coach: "Soft sounds come from small shakes. Big shakes make loud sounds." }],
        seconds: 40,
      },
      {
        type: "match",
        prompt: "Match each sound to its shake.",
        pairs: [
          { left: "📢 a loud boom", right: "a big shake" },
          { left: "🤫 a soft tap", right: "a small shake" },
          { left: "🔇 no sound", right: "no shake" },
        ],
        hint: "Bigger shake, louder sound. No shake, no sound.",
        seconds: 30,
      },
      {
        type: "sort",
        prompt: "Did sound make it shake, or did a shake make the sound?",
        buckets: ["A shake makes a sound", "A sound makes it shake"],
        items: [
          { text: "🎸 You pluck a string and hear a twang", bucket: 0 },
          { text: "🥁 You tap a drum and hear a boom", bucket: 0 },
          { text: "🍚 A loud bang makes rice hop on plastic", bucket: 1 },
          { text: "🎈 Singing near a balloon makes it buzz", bucket: 1 },
        ],
        hint: "Ask: what came first? If the sound came first, the sound made it shake.",
        seconds: 50,
      },
      {
        type: "sequence",
        prompt: "Put the bell in order.",
        steps: ["🔔 Tap the bell", "〰️ The bell shakes", "🎵 You hear it ring", "✋ Touch the bell and it stops"],
        hint: "The shake comes before the sound. Stopping the shake stops the sound.",
        seconds: 40,
      },
    ],
    check: [
      {
        q: "What is a vibration?",
        choices: ["A fast shake", "A bright light", "A cold wind"],
        answer: 0,
        why: "A vibration is a fast shake. Vibrations make sounds.",
      },
      {
        q: "How do you make a drum louder?",
        choices: ["Tap it softly", "Hit it harder", "Paint it red"],
        answer: 1,
        why: "Hitting harder makes a bigger shake, and big shakes are loud.",
      },
      {
        q: "A ringing bell is touched and held. What happens?",
        choices: ["It gets louder", "It plays a song", "The sound stops"],
        answer: 2,
        why: "Holding the bell stops the shaking, so the sound stops.",
      },
      {
        q: "A loud bang makes rice hop on a bowl. What does that show?",
        choices: ["Rice can hear", "Sound can make things shake", "Bowls can jump"],
        answer: 1,
        why: "The sound moved through the air and shook the plastic, so the rice hopped.",
      },
    ],
    task: {
      kind: "lab",
      prompt: "With a parent, make a rice drum: stretch plastic wrap over a bowl and sprinkle rice on top. Bang a pot next to it, softly and then loudly. Watch the rice. Then hum with your hand on your throat.",
      rubric: [
        "Made the rice drum with a parent",
        "Saw the rice hop when a sound was made",
        "Noticed loud bangs make the rice hop more than soft ones",
        "Felt the throat shake while humming",
      ],
    },
  },

  // 2. Light, seeing, materials and shadows (1-PS4-2, 1-PS4-3)
  {
    id: "sci-1.light",
    title: "Light Helps Us See",
    minutes: 15,
    stage: "grammar",
    standards: ["1-PS4-2", "1-PS4-3"],
    read: [
      "Close your eyes. Everything is dark. Now open them. You can see! Light helps us see.",
      "In a room with no light at all, you cannot see a thing. Not even your hand! We see things when light shines on them. Some things make their own light, like the Sun, a lamp, a fire and a firefly.",
      "Light can go through some things. Clear glass lets light through. We call it transparent. Wax paper lets a little light through. We call it translucent. Wood and cardboard block the light. We call them opaque.",
      "When something blocks the light, a shadow forms behind it. A shiny mirror does something else. It bounces the light! We say it reflects light.",
      "So remember: light helps us see. Some things let light through, some let a little through, and some block it.",
    ].join("\n\n"),
    keyIdeas: [
      "We can only see things when light shines on them.",
      "Clear things let light through, cloudy things let some through, and solid things block it.",
      "Blocked light makes a shadow. A mirror bounces light.",
    ],
    hook: {
      text: "Night falls in Whisperwood Forest. It is very dark. Then Pip the firefly glows! Now you can see the trees. Why does light help us see?",
    },
    teach: [
      {
        title: "We See With Light",
        teach:
          "Go into a closet and shut the door. Turn off the light. Can you see your hand? No! In the dark, we cannot see. We see things when light shines on them. Some things make their own light. The Sun does. A lamp does. A campfire does. A firefly does too! Other things, like a book, need light shining on them.",
        visual: {
          type: "compare",
          left: { title: "Makes its own light ✨", points: ["☀️ The Sun", "💡 A lamp", "🔥 A campfire", "✨ A firefly"] },
          right: { title: "Needs light on it 🔦", points: ["📕 A book", "🧸 A teddy bear", "🌳 A tree", "✋ Your hand"] },
        },
        probe: {
          type: "sort",
          prompt: "Does it make its own light, or does it need light on it?",
          buckets: ["Makes its own light ✨", "Needs light on it 🔦"],
          items: [
            { text: "☀️ the Sun", bucket: 0 },
            { text: "💡 a lamp", bucket: 0 },
            { text: "🔥 a campfire", bucket: 0 },
            { text: "📕 a book", bucket: 1 },
            { text: "🧸 a teddy bear", bucket: 1 },
            { text: "⚽ a ball", bucket: 1 },
          ],
          hint: "Would you see it in a totally dark room? Only light makers glow in the dark.",
          mistakes: [{ match: "book makes light", coach: "A book does not glow. In a dark closet you cannot see it. It needs light on it." }],
          seconds: 45,
        },
        think: {
          q: "You are in a room with no light at all. What can you see?",
          choices: ["Your toys", "Nothing at all", "Your hand"],
          answer: 1,
          why: "With no light, nothing can be seen. We need light to see.",
          hints: ["Toys don't glow. With no light on them, you can't see them.", "", "Your hand is there, but with no light on it, you can't see it."],
        },
        approaches: {
          analogy: "Light is like a helper that carries a picture of things to your eyes. With no helper, no picture gets there.",
          example: "At night, turn off the lights in your room. Your teddy bear is still on the bed, but you can't see it. Turn on a flashlight and shine it on the bear. Now you can see it!",
          simpler: {
            q: "Which one makes its own light?",
            choices: ["A lamp", "A spoon"],
            answer: 0,
            why: "A lamp glows. A spoon needs light shining on it.",
            hints: ["", "A spoon does not glow. In the dark, you could not see it."],
          },
        },
      },
      {
        title: "Clear, Cloudy or Blocked",
        teach:
          "Shine a flashlight at a window. The light goes right through! Clear things are transparent. Now shine it at wax paper. Only a little light gets through. Cloudy things are translucent. Now shine it at a book. No light gets through. Things that block light are opaque. What do you notice about each one?",
        visual: {
          type: "hotspots",
          title: "Shine a flashlight on...",
          center: "🔦",
          spots: [
            { label: "Transparent", icon: "🪟", detail: "Clear, like a window or plastic wrap. Light goes right through." },
            { label: "Translucent", icon: "📄", detail: "Cloudy, like wax paper. A little light gets through." },
            { label: "Opaque", icon: "📦", detail: "Like wood or cardboard. It blocks the light." },
          ],
        },
        probe: {
          type: "sort",
          prompt: "Shine a flashlight on each one. Where does it go?",
          buckets: ["All light through 🪟", "Some light through 📄", "No light through 📦"],
          items: [
            { text: "🪟 a clear window", bucket: 0 },
            { text: "🥤 a clear plastic cup", bucket: 0 },
            { text: "📄 wax paper", bucket: 1 },
            { text: "🧻 tissue paper", bucket: 1 },
            { text: "📦 a cardboard box", bucket: 2 },
            { text: "🪵 a wood block", bucket: 2 },
          ],
          hint: "Can you see clearly through it? A little? Or not at all?",
          mistakes: [{ match: "wax paper all light", coach: "Wax paper is cloudy. Only some light gets through it." }],
          seconds: 50,
        },
        think: {
          q: "Wax paper lets a little light through. What word fits it?",
          choices: ["Opaque", "Transparent", "Translucent"],
          answer: 2,
          why: "Translucent things let some light through, like wax paper.",
          hints: ["Opaque things block all light. Wax paper lets some through.", "Transparent things are clear. You can't see clearly through wax paper.", ""],
        },
        approaches: {
          analogy: "Think of a gate. A clear window is a wide open gate. Wax paper is a gate open just a crack. A wall of wood is a gate shut tight.",
          example: "Hold a clear cup up to a lamp: bright! Hold wax paper up: a soft glow. Hold a book up: dark. Three things, three ways.",
          simpler: {
            q: "Which one can you see through clearly?",
            choices: ["A wood door", "A clear window"],
            answer: 1,
            why: "A clear window is transparent. Light goes right through.",
            hints: ["Wood blocks the light. You can't see through it.", ""],
          },
        },
      },
      {
        title: "Shadows and Mirrors",
        teach:
          "Stand in the sunshine. Look at the ground. There is your shadow! Your body is opaque. It blocks the light. A shadow forms on the side away from the light. Now hold up a mirror. A shiny mirror bounces light. We say it reflects light. You can make a spot of light dance on the wall!",
        visual: {
          type: "flip",
          cards: [
            { front: "👤 Shadow", back: "A dark spot where light is blocked." },
            { front: "📦 Opaque", back: "Blocks light. Opaque things make shadows." },
            { front: "🪞 Mirror", back: "Shiny and smooth. It bounces light." },
            { front: "↩️ Reflect", back: "To bounce light back, like a mirror does." },
          ],
        },
        probe: {
          type: "cloze",
          text: "My body blocks the light, so it makes a {0}. A shiny {1} bounces the light.",
          blanks: [{ answers: ["shadow"] }, { answers: ["mirror"] }],
          bank: ["shadow", "mirror", "rainbow", "sponge"],
          hint: "Blocked light makes a dark spot. Shiny things bounce light.",
          mistakes: [{ match: "sponge", coach: "A sponge is not shiny. A mirror is shiny and bounces light." }],
          seconds: 30,
        },
        think: {
          q: "Why do you have a shadow on a sunny day?",
          choices: ["Your body blocks the light", "The ground is wet", "Your shoes are dark"],
          answer: 0,
          why: "Your body is opaque. It blocks sunlight, so a shadow forms.",
          hints: ["", "Wet or dry, the ground gets a shadow when light is blocked.", "Even with white shoes, you still have a shadow. Your body blocks the light."],
        },
        approaches: {
          analogy: "A shadow is like an umbrella's dry spot in the rain. The umbrella blocks the rain. Your body blocks the light.",
          example: "Shine a flashlight on a wall. Put your hand in front. A hand-shaped shadow appears! Move your hand away and the shadow is gone.",
          simpler: {
            q: "What makes a shadow?",
            choices: ["Something blocking light", "Something making noise"],
            answer: 0,
            why: "When light is blocked, a dark shadow forms behind the object.",
            hints: ["", "Noise does not make shadows. Blocking light does."],
          },
        },
      },
    ],
    activity: {
      type: "highlight",
      prompt: "Tap every sentence that is true.",
      sentences: [
        "🔦 We see things when light shines on them.",
        "🌑 In a totally dark room, you can see your toys.",
        "🪟 Light goes through a clear window.",
        "📦 A cardboard box lets all the light through.",
        "🪞 A mirror bounces light.",
        "👤 A shadow forms when light is blocked.",
      ],
      correct: [0, 2, 4, 5],
    },
    explain: {
      prompt: "Tell me why you cannot see in a totally dark room. Then tell me how a shadow is made.",
      keyPoints: ["We need light to see things", "Light shines on things so we can see them", "A shadow forms when something blocks light"],
    },
    mastery: [
      {
        type: "match",
        prompt: "Match each word to what it means.",
        pairs: [
          { left: "🪟 transparent", right: "lets all light through" },
          { left: "📄 translucent", right: "lets some light through" },
          { left: "📦 opaque", right: "blocks the light" },
          { left: "🪞 reflect", right: "bounces the light" },
        ],
        hint: "Think: window, wax paper, cardboard, mirror.",
        seconds: 45,
      },
      {
        type: "cloze",
        text: "In the dark, we {0} see. Light must {1} on things so we can see them.",
        blanks: [{ answers: ["cannot", "can't"] }, { answers: ["shine"] }],
        bank: ["cannot", "shine", "sing", "always"],
        hint: "Think of the dark closet. Could you see your hand?",
        mistakes: [{ match: "always", coach: "In a totally dark room we can't see at all. We need light." }],
        seconds: 35,
      },
      {
        type: "sort",
        prompt: "Will it make a dark shadow on the wall?",
        buckets: ["Dark shadow 👤", "No dark shadow"],
        items: [
          { text: "✋ your hand", bucket: 0 },
          { text: "📕 a book", bucket: 0 },
          { text: "🪵 a wood block", bucket: 0 },
          { text: "🪟 a clear glass", bucket: 1 },
          { text: "🧴 clear plastic wrap", bucket: 1 },
        ],
        hint: "Opaque things block light and make dark shadows. Clear things let light through.",
        seconds: 45,
      },
      {
        type: "sequence",
        prompt: "Make a shadow puppet. Put the steps in order.",
        steps: ["🌑 Turn off the room light", "🔦 Shine a flashlight at the wall", "✋ Put your hand in the light", "🐰 See a shadow on the wall"],
        hint: "First make it dark, then make light, then block it.",
        seconds: 40,
      },
    ],
    check: [
      {
        q: "What do we need to see things?",
        choices: ["Sound", "Wind", "Light"],
        answer: 2,
        why: "We see things when light shines on them.",
      },
      {
        q: "Which one makes its own light?",
        choices: ["The Sun", "A rock", "A shoe"],
        answer: 0,
        why: "The Sun glows with its own light. Rocks and shoes need light on them.",
      },
      {
        q: "Which one blocks light?",
        choices: ["A clear window", "A wood board", "Plastic wrap"],
        answer: 1,
        why: "Wood is opaque. It blocks the light.",
      },
      {
        q: "What does a mirror do with light?",
        choices: ["Eats it", "Hides it", "Bounces it"],
        answer: 2,
        why: "A shiny mirror reflects, or bounces, light.",
      },
    ],
    task: {
      kind: "lab",
      prompt: "With a parent, make the room dark and use a flashlight. Shine it at a window or clear cup, wax paper or a paper towel, and a book. Then make a shadow puppet on the wall.",
      rubric: [
        "Tested at least three things with the flashlight",
        "Told which let all light, some light or no light through",
        "Made a shadow by blocking the light",
        "Said that we need light to see",
      ],
    },
  },

  // 3. Sending messages with light and sound (1-PS4-4, K-2-ETS1)
  {
    id: "sci-1.signals",
    title: "Sending Messages Far Away",
    minutes: 20,
    stage: "rhetoric",
    standards: ["1-PS4-4", "K-2-ETS1-1", "K-2-ETS1-2", "K-2-ETS1-3"],
    read: [
      "Your friend is far away across the field. How can you send a message? You can use sound or light!",
      "Loud sounds travel far. Long ago, people beat drums and rang bells to send news. A whistle can call your team. A foghorn warns ships in thick fog.",
      "Light can be seen far away, too, most of all at night. A lighthouse flashes its light to warn ships about rocks. You can blink a flashlight in a code. One blink can mean yes. Two blinks can mean no.",
      "You can build your own message maker. Engineers solve problems in steps. First, ask what the problem is. Next, draw a plan. Then build it. Test it. Make it better!",
      "Try a cup phone. Poke a string through the bottoms of two cups. Pull the string tight. Talk into one cup. Your voice shakes the string, and your friend hears you in the other cup.",
    ].join("\n\n"),
    keyIdeas: [
      "We can send messages far away with sound or light.",
      "Lighthouses, flashlights, drums, bells and whistles all send signals.",
      "Engineers ask, plan, build, test and make it better.",
    ],
    hook: {
      text: "Pip has a problem. Pip wants to call a friend across Whisperwood Forest. The friend is too far to hear a whisper. How can Pip send a message far away?",
    },
    teach: [
      {
        title: "Calling With Sound",
        teach:
          "Loud sounds travel far. Long ago, people beat big drums to send news to the next village. Church and school bells rang to tell people the time. A coach blows a whistle to call the team. A ship's foghorn booms in thick fog so other ships know where it is. What sound could you use to call a friend?",
        visual: {
          type: "hotspots",
          title: "Sounds that send messages",
          center: "🔊",
          spots: [
            { label: "Drum", icon: "🥁", detail: "Long ago, people beat big drums to send news far away." },
            { label: "Bell", icon: "🔔", detail: "A bell can tell everyone it is time to come in." },
            { label: "Whistle", icon: "📯", detail: "A loud whistle calls the team together." },
            { label: "Foghorn", icon: "🚢", detail: "A deep boom that helps ships find each other in fog." },
          ],
        },
        probe: {
          type: "match",
          prompt: "Match each sound to its message.",
          pairs: [
            { left: "🔔 a school bell", right: "Time to come in!" },
            { left: "📯 a coach's whistle", right: "Team, come here!" },
            { left: "🚢 a foghorn", right: "A ship is near!" },
            { left: "⏰ an alarm clock", right: "Time to wake up!" },
          ],
          hint: "Think about who uses each sound and why.",
          seconds: 45,
        },
        think: {
          q: "Why is a loud sound good for sending a message far away?",
          choices: ["It is pretty", "It is quiet", "It travels far"],
          answer: 2,
          why: "Loud sounds travel far, so people far away can hear them.",
          hints: ["A pretty sound can still be too quiet. Loud is what matters.", "A quiet sound can't be heard far away.", ""],
        },
        approaches: {
          analogy: "A loud sound is like throwing a ball hard. A hard throw goes far. A soft toss lands close.",
          example: "Whisper to a friend across the yard. They can't hear you. Now ring a bell. They hear it and wave back!",
          simpler: {
            q: "Your friend is far away. Which is better to call them?",
            choices: ["A loud bell", "A tiny whisper"],
            answer: 0,
            why: "A loud bell's sound travels far.",
            hints: ["", "A whisper is too quiet to travel far."],
          },
        },
      },
      {
        title: "Signaling With Light",
        teach:
          "Light can be seen far away, most of all at night. A lighthouse stands by the sea. Its bright light flashes to warn ships about rocks. You can send messages with a flashlight too! Make a code. One blink means yes. Two blinks mean no. Three blinks mean come here. Now you can talk without a sound!",
        visual: {
          type: "flip",
          cards: [
            { front: "💡", back: "One blink: yes" },
            { front: "💡💡", back: "Two blinks: no" },
            { front: "💡💡💡", back: "Three blinks: come here" },
            { front: "🗼 Lighthouse", back: "Flashes its light to warn ships about rocks." },
          ],
        },
        probe: {
          type: "number",
          prompt: "In our code, three blinks mean come here. Pip says come here two times. How many blinks is that in all? 💡💡💡 💡💡💡",
          answer: 6,
          unit: "blinks",
          hint: "Count every light bulb: three and three more.",
          mistakes: [{ match: "3", coach: "That's one come here. Pip said it two times, so add three more." }],
          seconds: 30,
        },
        think: {
          q: "What does a lighthouse do?",
          choices: ["Warns ships about rocks", "Plays music", "Catches fish"],
          answer: 0,
          why: "A lighthouse flashes a bright light so ships stay safe from rocks.",
          hints: ["", "A lighthouse sends light, not music.", "A lighthouse is a tower with a light, not a fishing boat."],
        },
        approaches: {
          analogy: "A light code is like a secret handshake. Two friends agree what each blink means, then they can talk across the dark.",
          example: "At night, stand at one end of the hall with a flashlight. A parent stands at the other end. You ask, 'Want a snack?' They blink once: yes!",
          simpler: {
            q: "When is a flashlight easiest to see from far away?",
            choices: ["At noon", "At night"],
            answer: 1,
            why: "At night it is dark, so a small light shows up well.",
            hints: ["In bright daylight, a flashlight is hard to see.", ""],
          },
        },
      },
      {
        title: "Build It, Test It",
        teach:
          "Engineers solve problems in steps. First, ask: what is the problem? Pip needs to talk to a friend far away. Next, draw a plan. Then build it! Try a cup phone. Poke a string through two cups. Pull it tight. Talk into one cup. Your voice shakes the string. Test it. Then make it better!",
        visual: {
          type: "sequence",
          prompt: "How engineers work",
          steps: ["❓ Ask: what is the problem?", "✏️ Draw a plan", "🔨 Build it", "🧪 Test it", "⭐ Make it better"],
        },
        probe: {
          type: "sequence",
          prompt: "Put the engineer's steps in order.",
          steps: ["❓ Ask what the problem is", "✏️ Draw a plan", "🔨 Build it", "🧪 Test it", "⭐ Make it better"],
          hint: "You have to know the problem before you plan. You have to build before you test.",
          mistakes: [{ match: "test before build", coach: "You can't test a cup phone until you build it." }],
          seconds: 45,
        },
        think: {
          q: "Your cup phone is hard to hear. What could make it better?",
          choices: ["Let the string go loose", "Pull the string tight", "Cut the string"],
          answer: 1,
          why: "A tight string carries the shakes of your voice best.",
          hints: ["A loose string flops and the shakes fade away.", "", "With no string, the shakes have no path to travel."],
        },
        approaches: {
          analogy: "Building is like baking a new cake. You plan it, bake it, taste it, and then change the recipe to make it even better.",
          example: "Build two cup phones, one with a loose string and one with a tight string. Test both. The tight one is easier to hear, so it is the better design.",
          simpler: {
            q: "What do you do right after you build it?",
            choices: ["Test it", "Throw it away"],
            answer: 0,
            why: "After you build, you test it to see if it works.",
            hints: ["", "Don't give up! Test it first to see how well it works."],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "Does it send a message with light or with sound?",
      buckets: ["Light 💡", "Sound 🔊"],
      items: [
        { text: "🗼 a lighthouse", bucket: 0 },
        { text: "🔦 a flashlight code", bucket: 0 },
        { text: "🚦 a traffic light", bucket: 0 },
        { text: "🥁 a drum", bucket: 1 },
        { text: "🔔 a bell", bucket: 1 },
        { text: "📯 a whistle", bucket: 1 },
        { text: "🥤 a cup phone", bucket: 1 },
      ],
    },
    explain: {
      prompt: "Pip wants to send a message to a friend far away at night. Tell Pip one way to do it with light and one way with sound.",
      keyPoints: ["Use light like a flashlight or lighthouse", "Use a loud sound like a bell, drum or whistle", "Make a code so the friend knows what it means"],
    },
    mastery: [
      {
        type: "sequence",
        prompt: "Make a cup phone. Put the steps in order.",
        steps: ["✂️ Poke a hole in the bottom of each cup", "🧵 Tie the string through both cups", "↔️ Walk apart and pull the string tight", "🗣️ Talk into one cup", "👂 Your friend listens in the other cup"],
        hint: "You need cups and string before you can talk. The string must be tight.",
        seconds: 50,
      },
      {
        type: "number",
        prompt: "One blink means yes. Pip answers yes to 4 questions. How many blinks in all?",
        answer: 4,
        unit: "blinks",
        hint: "Each yes is one blink. Count one blink for each question.",
        seconds: 30,
      },
      {
        type: "cloze",
        text: "A lighthouse sends a message with {0}. A bell sends a message with {1}.",
        blanks: [{ answers: ["light"] }, { answers: ["sound"] }],
        bank: ["light", "sound", "water", "sand"],
        hint: "You see a lighthouse. You hear a bell.",
        seconds: 30,
      },
      {
        type: "match",
        prompt: "Pip built two cup phones and tested them. Match each one to how it worked.",
        pairs: [
          { left: "🧵 tight string", right: "easy to hear 😀" },
          { left: "〰️ loose string", right: "hard to hear 😕" },
        ],
        hint: "A tight string carries the shakes of your voice.",
        seconds: 25,
      },
    ],
    check: [
      {
        q: "Which one sends a message with light?",
        choices: ["A drum", "A lighthouse", "A whistle"],
        answer: 1,
        why: "A lighthouse flashes light to warn ships.",
      },
      {
        q: "Why does a cup phone work?",
        choices: ["Your voice shakes the string", "The cups have batteries", "The string glows"],
        answer: 0,
        why: "Your voice makes the string shake, and the shakes travel to the other cup.",
      },
      {
        q: "What do engineers do after they build something?",
        choices: ["Forget about it", "Hide it", "Test it"],
        answer: 2,
        why: "Engineers test what they build, then make it better.",
      },
      {
        q: "When is a flashlight signal easiest to see?",
        choices: ["At night", "At noon", "In a sunny field"],
        answer: 0,
        why: "In the dark, a small light stands out and can be seen far away.",
      },
    ],
    task: {
      kind: "project",
      prompt: "With a parent, build a cup phone with two cups and a long string. Test it with the string loose and then tight. Then make up a flashlight code and send a message at night.",
      rubric: [
        "Built a cup phone with a parent",
        "Tested it with a loose and a tight string and said which worked better",
        "Made a light code with at least two signals",
        "Sent a message that the parent understood",
      ],
    },
  },

  // 4. Plant and animal parts, and copying nature (1-LS1-1)
  {
    id: "sci-1.parts",
    title: "Nature's Clever Parts",
    minutes: 20,
    stage: "logic",
    standards: ["1-LS1-1", "K-2-ETS1-2"],
    read: [
      "Plants and animals have special parts. Their parts help them stay alive and grow.",
      "A plant has roots. Roots hold the plant in the ground and drink up water. The stem holds the plant up. Leaves catch sunlight to make food. Flowers make seeds. A rose has sharp thorns so animals won't eat it.",
      "Animals have clever parts too. A turtle has a hard shell to stay safe. A duck has webbed feet to paddle. An eagle has sharp eyes to spot food far below. A porcupine has sharp quills.",
      "People copy nature to solve problems! A man named George de Mestral saw burrs stuck to his dog. The burrs had tiny hooks. He copied them to make Velcro. Swim fins work like a duck's webbed feet. A bike helmet is hard like a turtle's shell.",
      "So when you have a problem, look at nature. What do you notice?",
    ].join("\n\n"),
    keyIdeas: [
      "Plant parts like roots, stems, leaves and thorns help plants live and grow.",
      "Animal parts like shells, webbed feet and sharp eyes help animals stay safe and get food.",
      "People copy plant and animal parts to make useful things, like Velcro and swim fins.",
    ],
    hook: {
      text: "A burr is a prickly seed ball. It sticks to your socks on a forest walk! Why is it so sticky? One man looked closely and made a great invention.",
    },
    teach: [
      {
        title: "Plant Parts at Work",
        teach:
          "Look at a plant. Every part has a job! Roots grow under the ground. They hold the plant tight and drink up water. The stem holds the plant up tall. Leaves catch sunlight to make food. Flowers make seeds for new plants. Some plants have thorns or spines. Ouch! They keep hungry animals away.",
        visual: {
          type: "hotspots",
          title: "Parts of a plant",
          center: "🌻",
          spots: [
            { label: "Roots", icon: "🪱", detail: "Hold the plant in the ground and drink up water." },
            { label: "Stem", icon: "🎋", detail: "Holds the plant up and carries water to the leaves." },
            { label: "Leaves", icon: "🍃", detail: "Catch sunlight to make food for the plant." },
            { label: "Flower", icon: "🌸", detail: "Makes seeds that grow into new plants." },
            { label: "Thorns", icon: "🌹", detail: "Sharp points that keep hungry animals away." },
          ],
        },
        probe: {
          type: "match",
          prompt: "Match each plant part to its job.",
          pairs: [
            { left: "roots", right: "drink up water 💧" },
            { left: "leaves", right: "catch sunlight ☀️" },
            { left: "flower", right: "make seeds 🌰" },
            { left: "thorns", right: "keep animals away 🚫" },
          ],
          hint: "Roots are under the ground. Leaves face the Sun. Thorns are sharp.",
          mistakes: [{ match: "leaves drink water", coach: "Roots drink water from the soil. Leaves catch sunlight." }],
          seconds: 45,
        },
        think: {
          q: "Which part holds a plant in the ground?",
          choices: ["The flower", "The leaves", "The roots"],
          answer: 2,
          why: "Roots grow down into the soil and hold the plant tight.",
          hints: ["Flowers are up high. They make seeds.", "Leaves are up in the air catching sunlight.", ""],
        },
        approaches: {
          analogy: "A plant is like a house. The roots are the base that holds it down. The stem is the walls. The leaves are solar panels that catch sunlight.",
          example: "Pull up a weed. See the roots hanging down, full of dirt? They were holding the weed in the soil and drinking water.",
          simpler: {
            q: "Which part catches sunlight?",
            choices: ["Leaves", "Roots"],
            answer: 0,
            why: "Leaves catch sunlight to make food.",
            hints: ["", "Roots are under the ground where there is no sunlight."],
          },
        },
      },
      {
        title: "Animal Parts at Work",
        teach:
          "Animals have clever parts too! A turtle has a hard shell. It hides inside to stay safe. A porcupine has sharp quills. A duck has webbed feet. They push the water like paddles. An eagle has sharp eyes. It spots a fish from high in the sky. A bird's beak helps it grab food.",
        visual: {
          type: "hotspots",
          title: "Clever animal parts",
          center: "🐾",
          spots: [
            { label: "Shell", icon: "🐢", detail: "A turtle hides in its hard shell to stay safe." },
            { label: "Quills", icon: "🦔", detail: "A porcupine's sharp quills keep enemies away." },
            { label: "Webbed feet", icon: "🦆", detail: "A duck's webbed feet push water like paddles." },
            { label: "Sharp eyes", icon: "🦅", detail: "An eagle can spot a fish from high in the sky." },
            { label: "Beak", icon: "🐦", detail: "A bird's beak helps it grab and eat food." },
          ],
        },
        probe: {
          type: "sort",
          prompt: "What does each part help the animal do?",
          buckets: ["Stay safe 🛡️", "Move 🏊", "Get food 🍽️"],
          items: [
            { text: "🐢 a turtle's shell", bucket: 0 },
            { text: "🦔 a porcupine's quills", bucket: 0 },
            { text: "🦆 a duck's webbed feet", bucket: 1 },
            { text: "🐦 a bird's wings", bucket: 1 },
            { text: "🦅 an eagle's sharp eyes", bucket: 2 },
            { text: "🐦 a bird's beak", bucket: 2 },
          ],
          hint: "Hard and sharp parts keep animals safe. Feet and wings help them move.",
          seconds: 50,
        },
        think: {
          q: "How do a duck's webbed feet help it?",
          choices: ["They help it see", "They help it paddle", "They help it sing"],
          answer: 1,
          why: "Webbed feet push the water like paddles, so the duck can swim.",
          hints: ["Ducks see with their eyes, not their feet.", "", "Ducks quack with their bill and throat, not their feet."],
        },
        approaches: {
          analogy: "Animal parts are like tools in a toolbox. A shell is a shield. Webbed feet are paddles. Sharp eyes are binoculars.",
          example: "Spread your fingers wide and push them through bath water. Not much push. Now close your fingers tight like a paddle. Much more push! That's why ducks have webbed feet.",
          simpler: {
            q: "Which part keeps a turtle safe?",
            choices: ["Its tail", "Its hard shell"],
            answer: 1,
            why: "A turtle hides inside its hard shell to stay safe.",
            hints: ["A tail is small and soft. It can't protect the turtle.", ""],
          },
        },
      },
      {
        title: "Copy Nature!",
        teach:
          "People copy nature to solve problems. Long ago, a man named George de Mestral walked his dog. Burrs stuck to his dog's fur! He looked closely. The burrs had tiny hooks. He copied them and made Velcro. Swim fins copy a duck's webbed feet. A bike helmet is hard like a turtle's shell. What could you copy?",
        visual: {
          type: "compare",
          left: { title: "In nature 🌿", points: ["Burrs with tiny hooks", "A duck's webbed feet", "A turtle's hard shell"] },
          right: { title: "What people made 🛠️", points: ["Velcro", "Swim fins", "A bike helmet"] },
        },
        probe: {
          type: "match",
          prompt: "What did people copy? Match each invention to its idea from nature.",
          pairs: [
            { left: "Velcro", right: "burrs with tiny hooks" },
            { left: "🤿 swim fins", right: "🦆 a duck's webbed feet" },
            { left: "⛑️ a helmet", right: "🐢 a turtle's hard shell" },
            { left: "🧤 warm mittens", right: "🐻 a bear's thick fur" },
          ],
          hint: "Ask: what job does it do? Then find the plant or animal with the same job.",
          seconds: 45,
        },
        think: {
          q: "George de Mestral copied burrs to make what?",
          choices: ["Velcro", "Glue", "Shoelaces"],
          answer: 0,
          why: "Burrs have tiny hooks that grab fur. Velcro copies those hooks.",
          hints: ["", "Glue is sticky and wet. Burrs grab with tiny hooks, like Velcro.", "Shoelaces tie. Burrs grab with tiny hooks."],
        },
        approaches: {
          analogy: "Copying nature is like copying a good idea from a friend who already solved the puzzle. Plants and animals have been solving problems for a long time.",
          example: "Your feet get cold in the snow. A polar bear has thick fur and fat to stay warm. So you wear thick wool socks and puffy boots. You copied the bear!",
          simpler: {
            q: "Swim fins copy which animal part?",
            choices: ["A bird's beak", "A duck's webbed feet"],
            answer: 1,
            why: "Fins push water like a duck's webbed feet.",
            hints: ["A beak helps a bird eat, not swim.", ""],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "Does the part help it stay safe, or get food and water?",
      buckets: ["Stay safe 🛡️", "Get food or water 🍽️"],
      items: [
        { text: "🌹 a rose's thorns", bucket: 0 },
        { text: "🌵 a cactus's spines", bucket: 0 },
        { text: "🐢 a turtle's shell", bucket: 0 },
        { text: "🦔 a porcupine's quills", bucket: 0 },
        { text: "🌱 a plant's roots", bucket: 1 },
        { text: "🍃 leaves catching sunlight", bucket: 1 },
        { text: "🦅 an eagle's sharp eyes", bucket: 1 },
        { text: "🐦 a bird's beak", bucket: 1 },
      ],
    },
    explain: {
      prompt: "Pick one plant or animal part. Tell me how it helps. Then tell me something people made by copying nature.",
      keyPoints: ["Names a plant or animal part", "Says how the part helps it live", "Names an invention that copies nature, like Velcro or swim fins"],
    },
    mastery: [
      {
        type: "cloze",
        text: "Roots drink up {0}. Leaves catch {1}. A turtle's {2} keeps it safe.",
        blanks: [{ answers: ["water"] }, { answers: ["sunlight"] }, { answers: ["shell"] }],
        bank: ["water", "sunlight", "shell", "feather", "rocks"],
        hint: "Roots are in wet soil. Leaves face the Sun. A turtle hides in its hard home.",
        seconds: 40,
      },
      {
        type: "match",
        prompt: "Match each animal to its clever part.",
        pairs: [
          { left: "🦆 duck", right: "webbed feet" },
          { left: "🦅 eagle", right: "sharp eyes" },
          { left: "🦔 porcupine", right: "sharp quills" },
          { left: "🐢 turtle", right: "hard shell" },
        ],
        hint: "Think about how each animal swims, hunts or stays safe.",
        seconds: 40,
      },
      {
        type: "build",
        prompt: "Build the sentence about copying nature.",
        tiles: ["A", "helmet", "is", "hard", "like", "a", "turtle's", "shell."],
        distractors: ["soft", "feather."],
        hint: "Helmets and shells are both hard and keep things safe.",
        seconds: 45,
      },
      {
        type: "sort",
        prompt: "Is it a plant part or an animal part?",
        buckets: ["Plant part 🌱", "Animal part 🐾"],
        items: [
          { text: "🍃 leaf", bucket: 0 },
          { text: "🌹 thorn", bucket: 0 },
          { text: "🌸 flower", bucket: 0 },
          { text: "🐢 shell", bucket: 1 },
          { text: "🐦 beak", bucket: 1 },
          { text: "🦆 webbed foot", bucket: 1 },
        ],
        hint: "Plants grow in the ground. Animals move around.",
        seconds: 40,
      },
    ],
    check: [
      {
        q: "What do a plant's roots do?",
        choices: ["Make seeds", "Catch sunlight", "Drink up water"],
        answer: 2,
        why: "Roots hold the plant in the ground and drink up water.",
      },
      {
        q: "Why does a rose have thorns?",
        choices: ["To keep animals away", "To make seeds", "To smell nice"],
        answer: 0,
        why: "Sharp thorns keep hungry animals from eating the plant.",
      },
      {
        q: "Velcro copies which part of nature?",
        choices: ["A turtle's shell", "Burrs with tiny hooks", "A bird's wing"],
        answer: 1,
        why: "George de Mestral copied the tiny hooks on burrs to make Velcro.",
      },
      {
        q: "A bike helmet is like which animal part?",
        choices: ["A duck's feet", "An eagle's eyes", "A turtle's shell"],
        answer: 2,
        why: "Both are hard and protect what is inside.",
      },
    ],
    task: {
      kind: "project",
      prompt: "With a parent, solve a problem by copying nature. Ideas: make a hand paddle like a duck's foot from a plastic bag and a glove, or a shell to protect an egg from a little drop. Draw your plan first, then build and test it.",
      rubric: [
        "Drew a plan before building",
        "Named the plant or animal part copied",
        "Built and tested the design with a parent",
        "Said one way to make it better",
      ],
    },
  },

  // 5. Parents and offspring (1-LS1-2, 1-LS3-1)
  {
    id: "sci-1.families",
    title: "Baby Animals and Their Parents",
    minutes: 20,
    stage: "logic",
    standards: ["1-LS1-2", "1-LS3-1"],
    read: [
      "Many baby animals need help. Their parents help them stay safe and get food.",
      "A mother duck leads her ducklings. They follow her in a line. A baby kangaroo, called a joey, rides in its mother's pouch. An emperor penguin dad keeps the egg warm on his feet. A mother crocodile carries her tiny babies in her mouth, very gently!",
      "Babies help too. A hungry baby bird opens its mouth wide and chirps. The parent hears and brings food. A lost lamb bleats, and its mother calls back.",
      "Babies grow up to be like their parents. Puppies grow into dogs. A sunflower seed grows into a sunflower. But babies are not exactly like their parents. Puppies from the same mother can have different spots and colors.",
      "Some babies look very different at first. A tadpole grows into a frog. A caterpillar becomes a butterfly.",
    ].join("\n\n"),
    keyIdeas: [
      "Parents help babies stay safe and get food.",
      "Babies call, cry and chirp to get help, and they follow their parents.",
      "Young plants and animals are like their parents, but not exactly the same.",
    ],
    hook: {
      text: "Peep, peep! Down by the creek, a mother duck leads her ducklings. Every duckling follows her in a line. Why do they stay so close?",
    },
    teach: [
      {
        title: "Parents Keep Babies Safe",
        teach:
          "Many animal parents keep their babies safe. A mother duck leads her ducklings to the water. A baby kangaroo, called a joey, rides in its mother's pouch. An emperor penguin dad keeps the egg warm on his feet. A mother crocodile carries her tiny babies in her mouth, very gently! What do you notice? Parents stay close.",
        visual: {
          type: "hotspots",
          title: "Parents keep babies safe",
          center: "💛",
          spots: [
            { label: "Duck", icon: "🦆", detail: "A mother duck leads her ducklings, and they follow in a line." },
            { label: "Kangaroo", icon: "🦘", detail: "A baby joey rides safe and warm in its mother's pouch." },
            { label: "Penguin", icon: "🐧", detail: "An emperor penguin dad holds the egg on his feet to keep it warm." },
            { label: "Crocodile", icon: "🐊", detail: "A mother crocodile gently carries her tiny babies in her mouth." },
          ],
        },
        probe: {
          type: "cloze",
          text: "A baby kangaroo rides in its mother's {0}. A penguin dad keeps the egg warm on his {1}.",
          blanks: [{ answers: ["pouch"] }, { answers: ["feet"] }],
          bank: ["pouch", "feet", "nest", "tail"],
          hint: "A kangaroo has a pocket on its tummy. A penguin balances the egg down low.",
          mistakes: [{ match: "nest", coach: "Emperor penguins don't build nests. The dad holds the egg on his feet." }],
          seconds: 35,
        },
        think: {
          q: "Why do ducklings follow their mother?",
          choices: ["To stay safe", "To play tag", "To find a toy"],
          answer: 0,
          why: "Staying close to mother keeps ducklings safe and helps them find food.",
          hints: ["", "They aren't playing. Mother leads them to food and away from danger.", "Ducks don't have toys. Following mother keeps them safe."],
        },
        approaches: {
          analogy: "It's like holding a grown-up's hand in a busy store. Staying close keeps you safe.",
          example: "A mother hen spreads her wings. Her chicks run under them. Under her wings they are warm and hidden from a hawk.",
          simpler: {
            q: "Where does a baby kangaroo ride?",
            choices: ["In a tree", "In its mother's pouch"],
            answer: 1,
            why: "A joey rides in its mother's pouch.",
            hints: ["Kangaroos hop on the ground. The joey rides in a pocket on mother.", ""],
          },
        },
      },
      {
        title: "Babies Call for Help",
        teach:
          "Babies help too! A hungry baby bird opens its mouth wide. It chirps and chirps. The parent hears it and brings a worm. A lost lamb bleats, baa! Its mother calls back, and they find each other. A human baby cries when it is hungry. Calling for help is how babies get what they need.",
        visual: {
          type: "flip",
          cards: [
            { front: "🐣 Chirp!", back: "A baby bird chirps with its mouth open wide. Feed me!" },
            { front: "🐑 Baa!", back: "A lamb bleats. Its mother calls back to find it." },
            { front: "👶 Waaah!", back: "A baby cries when it is hungry or needs help." },
          ],
        },
        probe: {
          type: "sequence",
          prompt: "Put the baby bird's lunch in order.",
          steps: ["🐣 The baby bird is hungry", "📢 It opens its mouth and chirps", "👂 The parent hears it", "🪱 The parent brings a worm", "😋 The baby eats"],
          hint: "The baby is hungry first. The parent can't bring food until it hears the chirp.",
          seconds: 45,
        },
        think: {
          q: "Why does a baby bird chirp with its mouth open?",
          choices: ["It is singing a song", "It is cold", "It wants food"],
          answer: 2,
          why: "Chirping with a wide open mouth tells the parent: I'm hungry!",
          hints: ["Baby birds aren't singing yet. They are asking for something.", "A cold chick snuggles under its parent. The open mouth asks for food.", ""],
        },
        approaches: {
          analogy: "A baby bird's chirp is like ringing a dinner bell. It tells the parent: time to eat!",
          example: "Watch a nest in spring from far away. When the parent lands, the chicks stretch up, open wide and chirp. The parent drops food right in.",
          simpler: {
            q: "What does a hungry baby bird do?",
            choices: ["Chirps", "Sleeps all day"],
            answer: 0,
            why: "It chirps so its parent knows it is hungry.",
            hints: ["", "A sleeping chick is quiet. A hungry chick chirps loudly."],
          },
        },
      },
      {
        title: "Alike, But Not the Same",
        teach:
          "Babies grow up to be like their parents. Kittens grow into cats. An acorn grows into an oak tree. But babies are not exactly the same! Kittens from one mother can have different colors. Some babies look very different at first. A tadpole has a tail and no legs. It grows into a frog. A caterpillar becomes a butterfly!",
        visual: {
          type: "compare",
          left: { title: "Like their parents ✅", points: ["Kittens grow into cats", "An acorn grows into an oak tree", "Puppies grow into dogs"] },
          right: { title: "Not exactly the same 🔍", points: ["Kittens can be different colors", "Some puppies have more spots", "A tadpole looks different from a frog"] },
        },
        probe: {
          type: "match",
          prompt: "Match each baby to its grown-up parent.",
          pairs: [
            { left: "🐣 chick", right: "🐔 hen" },
            { left: "tadpole", right: "🐸 frog" },
            { left: "🐛 caterpillar", right: "🦋 butterfly" },
            { left: "🌰 acorn", right: "🌳 oak tree" },
            { left: "joey", right: "🦘 kangaroo" },
          ],
          hint: "Some babies look a lot like their parents. Some change a lot as they grow.",
          seconds: 50,
        },
        think: {
          q: "Two kittens have the same mother. One is gray and one is orange. What does that show?",
          choices: ["They are not really cats", "Babies are like, but not exactly like, their parents", "They will turn into dogs"],
          answer: 1,
          why: "Both are cats like their mother, but each one looks a little different.",
          hints: ["They are still cats! Cats come in many colors.", "", "Kittens always grow into cats, never dogs."],
        },
        approaches: {
          analogy: "It's like cookies from the same batch. They are all cookies, but each one has a little different shape and chip pattern.",
          example: "A mother dog has four puppies. All four are dogs with tails, fur and four legs. But one has a white spot, one is all brown, and one has floppier ears.",
          simpler: {
            q: "What does a puppy grow into?",
            choices: ["A cat", "A dog"],
            answer: 1,
            why: "Puppies grow into dogs, like their parents.",
            hints: ["Puppies have dog parents, so they grow into dogs.", ""],
          },
        },
      },
    ],
    activity: {
      type: "sort",
      prompt: "How is the parent helping? Sort each one.",
      buckets: ["Keeps baby safe 🛡️", "Feeds baby 🍼"],
      items: [
        { text: "🦘 A joey hides in its mother's pouch", bucket: 0 },
        { text: "🐧 A penguin dad keeps the egg warm", bucket: 0 },
        { text: "🐈 A cat carries her kitten back to bed", bucket: 0 },
        { text: "🦆 A duck leads her ducklings away from a fox", bucket: 0 },
        { text: "🐦 A robin drops a worm into a chick's mouth", bucket: 1 },
        { text: "🐄 A cow gives her calf milk", bucket: 1 },
        { text: "🐕 A dog feeds her puppies milk", bucket: 1 },
      ],
    },
    explain: {
      prompt: "Tell me one way an animal parent helps its baby. Then tell me how a baby is like its parent, and how it is different.",
      keyPoints: ["Parents keep babies safe or feed them", "Babies call or follow to get help", "Babies grow up like their parents", "Babies are not exactly the same as their parents"],
    },
    mastery: [
      {
        type: "match",
        prompt: "Match each parent to how it helps.",
        pairs: [
          { left: "🦆 mother duck", right: "leads her ducklings" },
          { left: "🐧 penguin dad", right: "keeps the egg warm on his feet" },
          { left: "🦘 mother kangaroo", right: "carries her joey in a pouch" },
          { left: "🐦 robin", right: "brings worms to the chicks" },
        ],
        hint: "Think about each picture from the lesson.",
        seconds: 45,
      },
      {
        type: "cloze",
        text: "A tadpole grows into a {0}. A caterpillar grows into a {1}.",
        blanks: [{ answers: ["frog"] }, { answers: ["butterfly"] }],
        bank: ["frog", "butterfly", "fish", "bird"],
        hint: "Tadpoles live in ponds and grow legs. Caterpillars grow wings.",
        mistakes: [{ match: "fish", coach: "A tadpole swims like a fish, but it grows legs and becomes a frog." }],
        seconds: 30,
      },
      {
        type: "number",
        prompt: "A mother dog has 6 puppies. 2 puppies are black. The rest are brown. How many puppies are brown? 🐶🐶🐶🐶🐶🐶",
        answer: 4,
        unit: "puppies",
        hint: "Start with 6 puppies. Take away the 2 black ones.",
        mistakes: [{ match: "8", coach: "Take away the black puppies. Don't add them. 6 take away 2." }],
        seconds: 40,
      },
      {
        type: "sequence",
        prompt: "Put the frog's life in order.",
        steps: ["🥚 An egg in the pond", "A tadpole with a tail", "A tadpole growing legs", "🐸 A grown-up frog"],
        hint: "It starts as an egg. The legs grow before it becomes a frog.",
        seconds: 40,
      },
    ],
    check: [
      {
        q: "Where does a baby kangaroo ride?",
        choices: ["In its mother's pouch", "On a bird's back", "In a nest"],
        answer: 0,
        why: "A joey rides safe in its mother's pouch.",
      },
      {
        q: "A baby bird chirps with its mouth open. What does it want?",
        choices: ["A bath", "A nap", "Food"],
        answer: 2,
        why: "It is telling its parent it is hungry.",
      },
      {
        q: "What does an acorn grow into?",
        choices: ["A rose bush", "An oak tree", "A sunflower"],
        answer: 1,
        why: "Plants grow into the same kind of plant as their parents. Acorns grow into oaks.",
      },
      {
        q: "Puppies from the same mother can look different. What does that show?",
        choices: ["They are cats", "They are toys", "Babies are not exactly like their parents"],
        answer: 2,
        why: "Babies look like their parents, but each one is a little different.",
      },
    ],
    task: {
      kind: "speak",
      prompt: "With a parent, look at baby pictures of animals in a book or on a walk. Pick one animal. Tell how its parent helps it, and one way the baby looks like its parent and one way it looks different.",
      rubric: [
        "Named an animal and its baby",
        "Told one way the parent helps the baby",
        "Told one way the baby is like the parent",
        "Told one way the baby is different from the parent",
      ],
    },
  },

  // 6. Sun, Moon, stars and daylight (1-ESS1-1, 1-ESS1-2)
  {
    id: "sci-1.sky",
    title: "Patterns in the Sky",
    minutes: 20,
    stage: "logic",
    standards: ["1-ESS1-1", "1-ESS1-2"],
    read: [
      "Look up! The sky has patterns. A pattern is something that happens again and again.",
      "Every morning, the Sun rises in the east. At midday it is high in the sky. In the evening it sets in the west. It looks like the Sun moves. Really, the Earth is spinning!",
      "The Moon has a pattern too. Night by night, its shape seems to change. It goes from round and full, to a half, to a thin sliver, and back again. The pattern starts over about every month.",
      "Stars shine at night. In the day, the Sun is so bright that we cannot see the stars. But they are still there!",
      "Days change across the year. In summer, there are many hours of daylight. The Sun is still up after dinner. In winter, there are fewer hours of daylight. It gets dark early.",
      "Because these patterns repeat, we can predict them!",
    ].join("\n\n"),
    keyIdeas: [
      "The Sun rises in the east and sets in the west every day.",
      "The Moon's shape seems to change in a pattern that repeats about every month.",
      "Stars shine at night, and summer days have more daylight than winter days.",
    ],
    hook: {
      text: "Pip loves to watch the sky over Whisperwood. Every morning the Sun comes up. Every night the stars come out. Can we guess what the sky will do tomorrow?",
    },
    teach: [
      {
        title: "The Sun's Daily Trip",
        teach:
          "Every morning, the Sun rises in the east. At midday, it is high in the sky. In the evening, it sets in the west. Then it is night. This happens every single day! It looks like the Sun moves across the sky. Really, our Earth is spinning, like a slow top. A pattern that repeats is easy to predict.",
        visual: {
          type: "sequence",
          prompt: "The Sun's trip across the sky",
          steps: ["🌅 Morning: the Sun rises in the east", "☀️ Midday: the Sun is high", "🌇 Evening: the Sun sets in the west", "🌙 Night: the stars come out"],
        },
        probe: {
          type: "sequence",
          prompt: "Put one day in order.",
          steps: ["🌅 The Sun rises", "☀️ The Sun is high at midday", "🌇 The Sun sets", "🌌 Night with stars"],
          hint: "The Sun comes up first and goes down last.",
          mistakes: [{ match: "sets first", coach: "The Sun has to rise before it can set." }],
          seconds: 35,
        },
        think: {
          q: "Where does the Sun rise every morning?",
          choices: ["In the west", "In the east", "Straight overhead"],
          answer: 1,
          why: "The Sun rises in the east and sets in the west.",
          hints: ["The west is where the Sun sets in the evening.", "", "At sunrise the Sun is low near the ground, not overhead."],
        },
        approaches: {
          analogy: "Sit on a spinning chair and turn slowly. The lamp in the room seems to slide past you. That's like Earth spinning past the Sun.",
          example: "Look out the same window at breakfast, lunch and dinner. At breakfast the Sun is low on one side. At lunch it is high. At dinner it is low on the other side.",
          simpler: {
            q: "When does the Sun rise?",
            choices: ["In the morning", "At bedtime"],
            answer: 0,
            why: "The Sun rises every morning.",
            hints: ["", "At bedtime the Sun has already set."],
          },
        },
      },
      {
        title: "The Moon and the Stars",
        teach:
          "Look at the Moon each night. Its shape seems to change! Sometimes it is round and full. Then it shrinks to a half. Then it is a thin sliver. Then we can hardly see it. Then it grows back. The pattern starts over about every month. Stars shine at night. In the day, the bright Sun hides them. But they are still there!",
        visual: {
          type: "flip",
          cards: [
            { front: "🌕", back: "Full Moon: round and bright." },
            { front: "🌗", back: "Half Moon: we see half of it lit up." },
            { front: "🌘", back: "A thin sliver of Moon." },
            { front: "🌑", back: "New Moon: we can hardly see it at all." },
            { front: "⭐", back: "Stars are always there. In the day, the Sun is too bright to see them." },
          ],
        },
        probe: {
          type: "cloze",
          text: "The Moon's shape seems to {0}. The pattern starts over about every {1}. We see stars at {2}.",
          blanks: [{ answers: ["change"] }, { answers: ["month"] }, { answers: ["night"] }],
          bank: ["change", "month", "night", "year", "noon", "melt"],
          hint: "Think of the full Moon, the half Moon and the thin sliver.",
          mistakes: [
            { match: "noon", coach: "At noon the Sun is so bright that it hides the stars. We see stars at night." },
            { match: "year", coach: "The Moon's pattern is faster than a year. It starts over about every month." },
          ],
          seconds: 40,
        },
        think: {
          q: "Why can't we see stars in the daytime?",
          choices: ["The stars go away", "The stars fall down", "The Sun is too bright"],
          answer: 2,
          why: "The stars are still there. The bright Sun outshines them.",
          hints: ["The stars don't go anywhere. Something hides them.", "Stars don't fall. They are still up there in the day.", ""],
        },
        approaches: {
          analogy: "A flashlight looks bright in a dark room. Turn it on outside at noon and you can hardly see it. Stars are like that in the daytime.",
          example: "Look at the Moon tonight and draw it. Look again in one week and draw it again. The shape is different! In about a month, it looks like your first drawing again.",
          simpler: {
            q: "When do we see lots of stars?",
            choices: ["At night", "At noon"],
            answer: 0,
            why: "Stars show up at night when the Sun is not in the sky.",
            hints: ["", "At noon the bright Sun hides the stars."],
          },
        },
      },
      {
        title: "Long Days, Short Days",
        teach:
          "Days change across the year. In summer, the Sun comes up early and sets late. You can play outside after dinner! In much of our country, a summer day has about 15 hours of daylight. In winter, the Sun sets early. It is dark at dinner time. A winter day has about 9 hours of daylight. In spring and fall, it is in between.",
        visual: {
          type: "compare",
          left: { title: "Summer ☀️", points: ["More hours of daylight", "The Sun sets late", "Light after dinner"] },
          right: { title: "Winter ❄️", points: ["Fewer hours of daylight", "The Sun sets early", "Dark at dinner time"] },
        },
        probe: {
          type: "place",
          prompt: "Put each day on the line. How many hours of daylight does it have?",
          min: 0,
          max: 24,
          step: 1,
          tolerance: 1,
          items: [
            { label: "❄️ A winter day", value: 9 },
            { label: "🌷 A spring day", value: 12 },
            { label: "☀️ A summer day", value: 15 },
          ],
          hint: "Summer has the most daylight, about 15 hours. Winter has the least, about 9. Spring is in between.",
          mistakes: [{ match: "winter at 15", coach: "Winter days are short. Summer has the most daylight." }],
          seconds: 45,
        },
        think: {
          q: "When is it still light outside after dinner?",
          choices: ["In winter", "In summer", "Never"],
          answer: 1,
          why: "Summer days have more hours of daylight, so the Sun sets late.",
          hints: ["Winter days are short. It is often dark by dinner.", "", "In summer the Sun sets late, so it is light after dinner."],
        },
        approaches: {
          analogy: "Daylight is like your playtime outside. In summer you get a big long playtime. In winter, the playtime is shorter.",
          example: "In June, look outside at 8 o'clock at night. It's still light! In December, look outside at 6 o'clock. It's already dark.",
          simpler: {
            q: "Which season has more daylight?",
            choices: ["Winter", "Summer"],
            answer: 1,
            why: "Summer has the most hours of daylight.",
            hints: ["Winter has short days and long nights.", ""],
          },
        },
      },
    ],
    activity: {
      type: "sequence",
      prompt: "Put Pip's day and night in order.",
      steps: ["🌅 Sunrise in the east", "🍳 Breakfast in the morning", "☀️ The Sun high at midday", "🌇 Sunset in the west", "🌙 The Moon and stars come out"],
    },
    explain: {
      prompt: "Tell me a pattern you can see in the sky. Then tell me how summer days and winter days are different.",
      keyPoints: ["The Sun rises in the east and sets in the west", "The Moon's shape changes in a pattern", "Stars are seen at night", "Summer days have more daylight than winter days"],
    },
    mastery: [
      {
        type: "match",
        prompt: "Match each Moon picture to its name.",
        pairs: [
          { left: "🌕", right: "full Moon" },
          { left: "🌗", right: "half Moon" },
          { left: "🌑", right: "new Moon" },
        ],
        hint: "Full is round. Half is half lit. New is dark.",
        seconds: 30,
      },
      {
        type: "number",
        prompt: "A summer day has about 15 hours of daylight. A winter day has about 9 hours. How many more hours of daylight does the summer day have?",
        answer: 6,
        unit: "hours",
        hint: "Count up from 9 to 15.",
        mistakes: [{ match: "24", coach: "Don't add them. Find how many more: count up from 9 to 15." }],
        seconds: 45,
      },
      {
        type: "sort",
        prompt: "Summer or winter?",
        buckets: ["Summer ☀️", "Winter ❄️"],
        items: [
          { text: "Light outside after dinner", bucket: 0 },
          { text: "The most hours of daylight", bucket: 0 },
          { text: "Dark at dinner time", bucket: 1 },
          { text: "The fewest hours of daylight", bucket: 1 },
        ],
        hint: "Summer days are long. Winter days are short.",
        seconds: 35,
      },
      {
        type: "cloze",
        text: "The Sun rises in the {0} and sets in the {1}.",
        blanks: [{ answers: ["east"] }, { answers: ["west"] }],
        bank: ["east", "west", "ocean", "ground"],
        hint: "The Sun rises in the east.",
        seconds: 25,
      },
    ],
    check: [
      {
        q: "Where does the Sun set?",
        choices: ["In the east", "In the west", "Under the house"],
        answer: 1,
        why: "The Sun rises in the east and sets in the west.",
      },
      {
        q: "About how long until the Moon's shapes start over?",
        choices: ["About a month", "About an hour", "About ten years"],
        answer: 0,
        why: "The Moon's pattern of shapes repeats about every month.",
      },
      {
        q: "Why don't we see stars at noon?",
        choices: ["They are asleep", "They moved away", "The Sun is too bright"],
        answer: 2,
        why: "The stars are still there, but the bright Sun hides them.",
      },
      {
        q: "Which has more hours of daylight?",
        choices: ["A summer day", "A winter day", "They are the same"],
        answer: 0,
        why: "Summer days are long, with more hours of daylight than winter days.",
      },
    ],
    task: {
      kind: "lab",
      prompt: "With a parent, be a sky watcher for one week. Each evening, look at the Moon and draw its shape. Also write down what time it gets dark. Talk about what pattern you see.",
      rubric: [
        "Drew the Moon on several nights",
        "Noticed the Moon's shape changing",
        "Wrote down when it got dark",
        "Told about a pattern seen in the sky",
      ],
    },
  },
]);
